---
title: "Reset Built-in Rule Groups"
keywords: "Kubernetes, {ks_product-en}, cluster management, monitoring alerting, alert management, rule groups, delete rule groups"
description: "Describes how to reset built-in rule groups."
weight: 08
---

:ks_permission: **Rule Group Management**
:ks_navigation: **Monitoring Alerting > Rule Groups**


This section describes how to reset built-in rule groups.

[.admon.note,cols="a"]
|===
|Note

|
* {ks_product-en} only supports resetting built-in rule groups, not custom rule groups.
* There are no built-in rule groups in projects.
|===

[.admon.warning,cols="a"]
|===
|Warning

|
Rule groups cannot be recovered after resetting, so please proceed with caution.
|===


== Prerequisites

* **WhizardTelemetry Alerting** should have been installed and enabled.

* {empty}
include::../../../../../_custom-en/clusterManagement/clusterManagement-prer-requiredPermission_new.adoc[]


== Steps

. Log in to the {ks_product-en} web console with a user who has the pass:a,q[{ks_permission}] permission and enter your cluster.

+

include::../../../../../../_ks_components-en/oper-navigate.adoc[]

+

. On the **Rule Groups** page, click **Built-in Rule Groups** to open the rule group list.

. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] on the right side of the rule group you need to reset, and then select **Reset** from the dropdown list.

. In the **Reset Rule Group** dialog, click **OK**.