---
title: "View Constraint Template Details"
description: "Learn how to view constraint template details."
weight: 03
---

:ks_permission: ** cluster-admin **
:ks_navigation: ** Gatekeeper > Constraint Templates**


This section describes how to view constraint template details.


== Prerequisites


* {empty}
include::../../../../_custom-en/clusterManagement/clusterManagement-prer-requiredPermission_new.adoc[]

* **Gatekeeper** should have been installed and enabled.

== Steps

include::../../../../_custom-en/clusterManagement/clusterManagement-oper-openClusterPage.adoc[]

+

include::../../../../../_ks_components-en/oper-navigate.adoc[]

+

. Click the name of a constraint template in the constraint template list to open its details page.

. In the **Attributes** area on the left side of the details page, view the basic information of the constraint template.
+
--

[%header,cols="2,5"]
|===
|Parameter |Description

|Cluster
|The cluster to which the constraint template belongs.

|Creation Time
|The creation time of the constraint template.

|CRD
|The CRD name corresponding to the constraint template.
|===
--

. In the **Targets** tab on the right side of the details page, view the constraint objects of the constraint template.

. Click the **Status** tab on the right side of the details page to view the labels and annotations of the constraint template.

. Click the **Constraints** tab on the right side of the details page to view the constraints created using the constraint template.