---
title: "View Volume Snapshot Content Details"
keywords: "Kubernetes, {ks_product-en}, cluster management, volume snapshot content, view volume snapshot content details"
description: "Learn how to view the details of a volume snapshot content."
weight: 07
---

:ks_permission: **Volume Snapshot Contents Viewing**
:ks_navigation: **Storage > Volume Snapshots**


This section describes how to view the details of a volume snapshot content.


== Prerequisites

* **KubeSphere Storage** should have been installed and enabled.

* {empty}
include::../../../../_custom-en/clusterManagement/clusterManagement-prer-requiredPermission_new.adoc[]

== Steps

include::../../../../_custom-en/clusterManagement/clusterManagement-oper-openClusterPage.adoc[]

+

include::../../../../../_ks_components-en/oper-navigate.adoc[]

+

. Click **Volume Snapshot Content** on the **Volume Snapshots** page, then click the name of a volume snapshot content to open its details page.

. View the resource attributes of the volume snapshot content in the **Attributes** area on the left side of the details page.
+
--

[%header,cols="1a,4a"]
|===
|Parameter |Description

|Status
|
include::../../../../_custom-en/clusterManagement/volumeSnapshotContents/volumeSnapshotContents-para-status.adoc[]

|Capacity
|
include::../../../../_custom-en/clusterManagement/volumeSnapshotContents/volumeSnapshotContents-para-capacity.adoc[]

|Volume Snapshot Class
|
include::../../../../_custom-en/clusterManagement/volumeSnapshotContents/volumeSnapshotContents-para-volumeSnapshotClass.adoc[]

|Snapshot Handle
|The unique identifier of the volume snapshot content in the backend storage system.

|Provisioner
|The storage plugin corresponding to the volume snapshot class.

|Deletion Policy
|
include::../../../../_custom-en/clusterManagement/volumeSnapshotContents/volumeSnapshotContents-para-deletionPolicy.adoc[]

|Creation Time
|The creation time of the volume snapshot content.

|Creator
|The user who created the volume snapshot content.
|===
--

. View the volume snapshot name and volume snapshot class of the volume snapshot content in the **Resource Status** tab on the right side of the details page.

. Click the **Metadata** tab on the right side of the details page to view the labels and annotations of the volume snapshot content.

. Click the **Events** tab on the right side of the details page to view the events of the volume snapshot content.
+
--
include::../../../../_custom-en/clusterManagement/clusterManagement-para-eventsTab.adoc[]
--