---
title: "Create Silence Policies"
keywords: "Kubernetes, {ks_product-en}, platform settings, notification management, notification settings, silence policy, create silence policy"
description: "This section describes how to create a silence policy."
weight: 01
---

:ks_navigation: **Notification Management > Notification Settings**
:ks_permission: **Platform Settings Management**


This section describes how to create a silence policy.


== Prerequisites

* {empty}
include::../../../../../_custom-en/platformManagement/platformManagement-prer-requiredPermission_v4.adoc[]

* **WhizardTelemetry Notification** should have been installed and enabled.


== Steps

include::../../../../../_custom-en/platformManagement/platformManagement-oper-logIn.adoc[]

. Click image:/images/ks-qkcp/zh/icons/cogwheel.svg[cogwheel,18,18] in the upper-right corner of the {ks_product-en} web console to enter the **Platform Settings** page.

+

include::../../../../../../_ks_components-en/oper-navigate.adoc[]

+

include::../../../../../../_ks_components-en/oper-clickCreate.adoc[]

+

. On the **Basic Information** tab, set the basic information for the silence policy, and then click **Next**.
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

|Name
|The name of the silence policy. The name can only contain lowercase letters, numbers, and hyphens (-), must start with a lowercase letter and end with a lowercase letter or number, and can be up to 63 characters long.

include::../../../../../_custom-en/platformManagement/platformSettings/platformSettings/platformSettings-para-aliasDescription.adoc[]
|===
--

. On the **Silence Conditions** tab, select **Silent for All Notifications** or **Custom Silence Conditions** as needed and set the relevant parameters, and then click **Next**.
+
====
include::../../../../../_custom-en/platformManagement/platformSettings/platformSettings/platformSettings-para-silenceConditions_new.adoc[]
====

. On the **Silence Time** tab, select the silence time type and set the relevant parameters, and then click **Create**.
+
--
include::../../../../../_custom-en/platformManagement/platformSettings/platformSettings/platformSettings-para-silenceTime.adoc[]

After the silence policy is created, it will be displayed in the silence policy list.
--