---
title: "Edit Silence Policy Information"
keywords: "Kubernetes, {ks_product-en}, platform settings, notification management, notification settings, silence policy, edit silence policy information"
description: "This section describes how to edit silence policy information."
weight: 02
---


:ks_navigation: **Notification Management > Notification Settings**
:ks_permission: **Platform Settings Management**


This section describes how to edit silence policy information.

You can edit the alias and description of a silence policy. KubeSphere does not support editing the name of a created silence policy.


== Prerequisites

* {empty}
include::../../../../../_custom-en/platformManagement/platformManagement-prer-requiredPermission_v4.adoc[]

* **WhizardTelemetry Notification** should have been installed and enabled.


== Steps

include::../../../../../_custom-en/platformManagement/platformManagement-oper-logIn.adoc[]

. Click image:/images/ks-qkcp/zh/icons/cogwheel.svg[cogwheel,18,18] in the upper-right corner of the {ks_product-en} web console to enter the **Platform Settings** page.

+

include::../../../../../../_ks_components-en/oper-navigate.adoc[]

+

. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] on the right side of the silence policy you need to edit, and then select **Edit Information** from the dropdown list.

. In the **Edit Information** dialog, set the alias and description of the silence policy, and then click **OK**.
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

include::../../../../../_custom-en/platformManagement/platformSettings/platformSettings/platformSettings-para-aliasDescription.adoc[]
|===
--