---
title: "Delete Silence Policies"
keywords: "Kubernetes, {ks_product-en}, platform settings, notification management, notification settings, silence policy, delete silence policy"
description: "This section describes how to delete a silence policy."
weight: 05
---

:ks_navigation: **Notification Management > Notification Settings**
:ks_permission: **Platform Settings Management**


This section describes how to delete a silence policy.


== Prerequisites

* {empty}
include::../../../../../_custom-en/platformManagement/platformManagement-prer-requiredPermission_v4.adoc[]

* **WhizardTelemetry Notification** should have been installed and enabled.

== Delete a Single Silence Policy

include::../../../../../_custom-en/platformManagement/platformManagement-oper-logIn.adoc[]

. Click image:/images/ks-qkcp/zh/icons/cogwheel.svg[cogwheel,18,18] in the upper-right corner of the {ks_product-en} web console to enter the **Platform Settings** page.

+

include::../../../../../../_ks_components-en/oper-navigate.adoc[]

+

. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] on the right side of the silence policy you need to delete, and then select **Delete** from the dropdown list.

. In the **Delete Silence Policy** dialog, enter the name of the silence policy, and then click **OK**.


== Delete Multiple Silence Policies

include::../../../../../_custom-en/platformManagement/platformManagement-oper-logIn.adoc[]

. Click image:/images/ks-qkcp/zh/icons/cogwheel.svg[cogwheel,18,18] in the upper-right corner of the {ks_product-en} web console to enter the **Platform Settings** page.

+

include::../../../../../../_ks_components-en/oper-navigate.adoc[]

+

. Select the checkbox on the left side of the silence policies you need to delete, and then click **Delete** above the list.

. In the **Delete Multiple Silence Policies** dialog, enter the names of the silence policies, and then click **OK**.
+
--
include::../../../../../_custom-en/note-separateNamesByComma.adoc[]
--