---
title: "Enable Log Collection in a Project"
keywords: "Kubernetes, {ks_product-en}, project management, project settings, log collection, enable log collection"
description: "This section introduces how to enable log collection."
weight: 02
---

:ks_permission: **Project Settings Management**
:ks_navigation: **Project Settings > Log Collection**

This section introduces how to enable log collection in a project.
//note
[.admon.note,cols="a"]
|===
|Note

|
After enabling, the **Collect Logs on Volumes** feature will be available on the **Storage Settings** tab when creating workloads and Jobs in the project.
|===

== Prerequisites

* {empty}
include::../../../../../_custom-en/projectManagement/projectManagement-prer-requiredPermission_new.adoc[]

* **WhizardTelemetry Logging** should have been installed and enabled, and link:../01-enable-logsidecar/[the log collection feature have been enabled].

== Steps

include::../../../../../_custom-en/projectManagement/projectManagement-oper-openProjectPage.adoc[]

+

include::../../../../../../_ks_components-en/oper-navigate.adoc[]

+

. In the **Collect Logs on Volumes** area, click the switch to set the status to **Enabled**.

// Note
include::../../../../../../_ks_components-en/admonitions/note.adoc[]

ifeval::["{file_output_type}" == "html"]
After enabling log collection, you need to restart the existing pods to make the change take effect. For more information, see link:../../../../../09-project-management/03-application-workloads/03-workloads/05-re-create-a-workload/[Recreate Workloads], link:../../../../../09-project-management/03-application-workloads/04-jobs/05-rerun-a-job/[Re-run Jobs], or link:../../../../../09-project-management/03-application-workloads/06-pods/05-delete-pods/[Delete Pods].
endif::[]

ifeval::["{file_output_type}" == "pdf"]
After enabling log collection, you need to restart the existing pods to make the change take effect. For more information, see the “Application Workloads” chapter of the {ks_product-en} Project Management Guide to recreate a workload, re-run a job, or delete pods.
endif::[]

include::../../../../../../_ks_components-en/admonitions/admonEnd.adoc[]