---
title: "创建和管理 DevOps 项目"
keywords: "Kubernetes, {ks_product}, DevOps 项目, DevOps 项目管理"
description: "演示如何创建和管理 DevOps 项目。"
weight: 01
---

本节演示如何创建和管理 DevOps 项目。

== 前提条件

ifeval::["{file_output_type}" == "html"]
* 已创建一个企业空间和一个用户 (**project-admin**)，需要邀请该用户至该企业空间并赋予 **workspace-self-provisioner** 角色。有关更多信息，请参阅link:../../../../02-quickstart/03-control-user-permissions[控制用户权限]。
endif::[]

ifeval::["{file_output_type}" == "pdf"]
* 已创建一个企业空间和一个用户 (**project-admin**)，需要邀请该用户至该企业空间并赋予 **workspace-self-provisioner** 角色。有关更多信息，请参阅《{ks_product_right}快速入门》的“控制用户权限”章节。
endif::[]

* {ks_product_right}平台需要安装并启用 **DevOps** 扩展组件。



== 创建 DevOps 项目

. 以 **project-admin** 用户登录{ks_product_left} Web 控制台，进入一个企业空间。

. 点击 **DevOps 项目**，然后点击**创建**。

. 输入 DevOps 项目的基本信息，然后点击**确定**。
+
--
* **名称**：DevOps 项目的简明名称，便于用户识别，例如 **demo-devops**。

* **别名**：DevOps 项目的别名。

* **描述信息**：DevOps 项目的简要介绍。

* **集群设置**：在当前版本中，DevOps 项目无法同时跨多个集群运行。如果有多个集群，则必须选择一个集群来运行 DevOps 项目。
--

. DevOps 项目创建后，会显示在 DevOps 项目页面的列表中。


== 查看 DevOps 项目

点击刚刚创建的 DevOps 项目，转到其详情页面。

在 DevOps 项目中，用户可以创建 CI/CD 流水线、凭证，以及管理项目成员和角色。根据权限不同，用户在 DevOps 项目中可以执行的操作也不同。

* 流水线
+
--
流水线是一系列插件的集合，支持持续地集成、测试和构建代码。流水线将持续集成 (CI) 和持续交付 (CD) 进行结合，提供精简的工作流，使您的代码可以自动交付给任何目标。
--

* 凭证
+
--
具有相应权限的 DevOps 项目用户可以为流水线配置凭证，以便与外部环境进行交互。用户在 DevOps 项目中添加凭证后，DevOps 项目就可以使用这些凭证与第三方应用程序（例如 GitHub、GitLab 和 Docker Hub）进行交互。有关更多信息，请参阅link:../../03-how-to-use/05-devops-settings/01-credential-management/[凭证管理]。
--

* 成员和角色
+
--
与项目相似，DevOps 项目也需要为用户授予角色，以便用户在 DevOps 项目拥有不同的权限。项目管理员（例如 **project-admin**）负责邀请用户并授予他们不同的角色。有关更多信息，请参阅link:../../03-how-to-use/05-devops-settings/02-role-and-member-management/[角色和成员管理]。
--

== 编辑或删除 DevOps 项目

. 点击 **DevOps 项目设置**下的**基本信息**，查看当前 DevOps 项目的概述，如项目角色和项目成员的数量、项目名称和项目创建者等。

. 点击右侧的**管理**按钮，编辑此 DevOps 项目的基本信息或删除 DevOps 项目。
