---
title: "Edit Log Receiver Settings"
keywords: "Kubernetes, {ks_product-en}, cluster management, cluster settings, log receivers, edit log receiver settings"
description: "This section introduces how to edit log receiver settings."
weight: 04
---

:ks_permission: **Cluster Settings Management**
:ks_navigation: **Cluster Settings > Log Receivers**

This section introduces how to edit log receiver settings.

== Prerequisites

* {empty}
include::../../../../../../_custom-en/clusterManagement/clusterManagement-prer-requiredPermission_new.adoc[]

* A log receiver has been added.

== Steps

include::../../../../../../_custom-en/clusterManagement/clusterManagement-oper-openClusterPage.adoc[]

+

include::../../../../../../../_ks_components-en/oper-navigate.adoc[]

+

. On the **Log Receivers** page, click **Container Logs**, **Resource Events**, **Audit Logs**, or **Notification History**, then click the name of a log receiver in the list to open its details page.

+

. Click **Edit** in the upper left corner of the details page.

. Modify the settings of the log receiver in the pop-up dialog, then click **OK**.
+
--
include::../../../../../../_custom-en/clusterManagement/logReceivers/logReceivers-para-addLogReceiver.adoc[]

[.admon.attention,cols="a"]
|===
|Attention

|
After modification, ensure that the `endpoints` of each extension under the configuration of **WhizardTelemetry Platform Service** is consistent with the modified service address, so that the {ks_product-en} platform can correctly query the log data. For more information, see the details page of the "WhizardTelemetry Platform Service" extension in the Extensions Center.

|===
--