---
title: "View Alert List"
keywords: "Kubernetes, {ks_product-en}, platform management, Whizard Observability Center, alert management, alerts, view alert list"
description: "Describes how to view the global alert list in the Whizard Observability Center."
weight: 01
---

// :ks_permission: **Alert Viewing**
:ks_navigation: **Global Alerts > Built-in Alerts/Custom Alerts**


This section describes how to view the global alert list in the Whizard Observability Center.

The **Built-in Alerts** and **Custom Alerts** pages in the Whizard Observability Center display alerts generated by the system based on global alerting rule groups, not including alerts generated by cluster and project alerting rule groups.


== Prerequisites

You should have the **platform-admin** role on the {ks_product-en} platform. For more information, see link:../../../../../../05-users-and-roles/01-users/[Users] and link:../../../../../../05-users-and-roles/02-platform-roles/[Platform Roles].

== Steps

include::../../../../../../_custom-en/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

+

. Click image:/images/ks-qkcp/zh/icons/grid.svg[grid,18,18] in the upper-right corner of the page and click **Whizard Observability Center**.

+

include::../../../../../../../_ks_components-en/oper-navigate.adoc[]

+

// include::../../../../../../_custom-en/clusterManagement/alerts/alerts-oper-openListPage.adoc[]
+
====
include::../../../../../../_custom-en/clusterManagement/alerts/alerts-para-alertingMessageList.adoc[]

include::../../../../../../_custom-en/clusterManagement/alerts/alerts-oper-searchForAlertingMessages_new.adoc[]

include::../../../../../../../_ks_components-en/oper-refreshListData.adoc[]

include::../../../../../../../_ks_components-en/oper-customizeColumns.adoc[]
====