---
title: "通过代理连接添加成员集群"
keywords: "Kubernetes, KubeSphere, 多集群管理, 集群, 添加成员集群, 通过代理连接添加成员集群"
description: "介绍如何通过代理连接添加成员集群。"
weight: 02
---


本节介绍如何通过代理连接添加成员集群。

如果主集群无法访问成员集群的 Kubernetes API 服务，您可以设置成员集群连接到主集群对外暴露的 **tower** 服务从而添加成员集群。


== 前提条件

* 您需要在主集群中具有 **platform-admin** 角色。

* {ks_product_right}平台需要安装并启用 **KubeSphere 多集群代理连接**扩展组件。

* 成员集群所有节点必须能访问主集群 **tower** 服务的外部访问地址。取决于您的网络环境，您可能需要配置防火墙和流量转发规则。

== 设置代理服务地址

在主集群安装“KubeSphere 多集群代理连接”扩展组件后，将在系统项目 kubesphere-system 中自动创建一个名为 tower 的服务。


=== 集群中有可用的 LoadBalancer

如果主集群中有可用的 LoadBalancer 插件，在主集群节点执行以下命令，可以看到 tower 服务有相应的 `EXTERNAL-IP` 地址。该地址将由 KubeSphere 自动获取并配置代理服务地址，这意味着您可以跳过设置代理服务地址这一步。

执行以下命令确认是否有 LoadBalancer 插件。

[,bash]
----
kubectl -n kubesphere-system get svc
----

命令输出结果可能如下所示：

[,bash]
----
NAME       TYPE            CLUSTER-IP      EXTERNAL-IP     PORT(S)              AGE
tower      LoadBalancer    10.233.63.191   139.198.110.23  8080:30721/TCP       16h
----

[.admon.note,cols="a"]
|===
|说明

|
主流公有云厂商一般会提供 LoadBalancer 解决方案，并且负载均衡器可以自动分配外部 IP。如果您的集群运行在本地环境中，尤其是在裸机环境中，可以使用 link:https://github.com/kubesphere/openelb[OpenELB] 作为负载均衡器解决方案。
|===

=== 集群中没有可用的 LoadBalancer

若主集群中没有可用的 LoadBalancer，执行 `kubectl -n kubesphere-system get svc` 命令后，输出结果可能如下所示。

[,bash]
----
NAME       TYPE            CLUSTER-IP      EXTERNAL-IP     PORT(S)              AGE
tower      LoadBalancer    10.233.63.191   <pending>       8080:30721/TCP       16h
----

由于 `EXTERNAL-IP` 处于 `pending` 状态，您需要手动设置代理地址，将 proxyPublishAddress 的值添加到 `kubesphere-config` ConfigMap 中。

. 在主集群节点，执行以下命令打开 kubesphere-config 配置字典。
+
[,bash]
----
kubectl -n kubesphere-system edit cm kubesphere-config
----

. 搜索 `multicluster` 并添加新行，输入 `proxyPublishAddress` 来定义 tower 服务的外部 IP 地址，以便访问 Tower。
+
--
[,bash]
----
multicluster:
  clusterRole: host
  proxyPublishAddress: {公有 IP 地址}:{Port} # Add this line to set the address to access tower
----

[.admon.note,cols="a"]
|===
|说明

|
您可能需要配置端口转发规则，例如，将公有 IP:Port 转发到 NodeIP:NodePort。
|===
--

== 添加成员集群

include::../../../_custom/platformManagement/multiclusterManagement/clusters/clusters-oper-logInToHost.adoc[]

+

. 点击**集群管理**。
+
include::../../../_custom/platformManagement/multiclusterManagement/clusters/clusters-oper-addClusterBasicInfo.adoc[]
+
在**高级设置**下，设置集群的用途标识。

. 在**连接设置**页签，将**连接方式**设置为**代理连接**，点击**下一步**。

. 在**集群配置**页签，设置集群配置，然后点击**创建**。
+
--
成员集群添加完成后将显示在**集群管理**页面的集群列表中。
--
