---
title: "Set Up Feishu Notification"
keywords: "Kubernetes, {ks_product-en}, platform settings, notification management, notification settings, set up Feishu notification"
description: "Describes how to set up Feishu notification."
weight: 02
---

// :ks_navigation: **Notification Management > Notification Channels**


This section describes how to set up Feishu notification.

Feishu notification functionality supports sending notifications to users through the following two methods:

* **Chat Settings**: Use a Feishu application to send notifications to specific users or departments.

* **Chatbot Settings**: Use a Feishu chatbot to send notifications to specific group chats.


== Prerequisites

* **WhizardTelemetry Notification** should have been installed and enabled.

* You should get the access parameters for the application or chatbot from Feishu in advance. For more information, see link:https://open.feishu.cn/document/ukTMukTMukTM/uITNz4iM1MjLyUzM[Feishu Developer Documentation].


== Steps

. Log in to the {ks_product-en} web console.

. Click the current username in the upper-right corner of the page, and then select **Notification Settings** from the dropdown list.

. On the **Notification Settings** page, under the **Feishu** tab, set the Feishu notification parameters, and then click **OK**.

+
====
* Chat Settings
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

// |App ID
// |The App ID of the Feishu application.

// |App Secret
// |The App Secret of the Feishu application.

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sessionId.adoc[]
|===
--

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-groupChatBotSettings.adoc[]

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-notificationConditions_new.adoc[]

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sendTestInformation.adoc[]
====

. Click the **Notification Disabled** switch above to enable Feishu notifications.