---
title: "Set Up DingTalk Notification"
keywords: "Kubernetes, {ks_product-en}, platform settings, notification management, notification settings, set up DingTalk notification"
description: "Describes how to set up DingTalk notification."
weight: 03
---

// :ks_navigation: **Notification Management > Notification Channels**


This section describes how to set up DingTalk notification.

DingTalk notification functionality supports sending notifications to users through the following two methods:

* **Chat Settings**: Use a DingTalk application to send notifications to specific users or departments.

* **Chatbot Settings**: Use a DingTalk chatbot to send notifications to specific group chats.

== Prerequisites

* **WhizardTelemetry Notification** should have been installed and enabled.

* You should get the access parameters for the application or chatbot from DingTalk in advance. For more information, see link:https://open.dingtalk.com/document/orgapp-server/how-to-call-apis[DingTalk Developer Documentation].


== Steps

. Log in to the {ks_product-en} web console.

. Click the current username in the upper-right corner of the page, and then select **Notification Settings** from the dropdown list.

. On the **Notification Settings** page, under the **DingTalk** tab, set the DingTalk notification parameters, and then click **OK**.

+
====
* Chat Settings
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

// |App Key
// |The App Key of the DingTalk application.

// |App Secret
// |The App Secret of the DingTalk application.

|Chat ID
|The Chat ID that will receive notifications. Click **Add** to set multiple Chat IDs.
|===
--

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-groupChatBotSettings.adoc[]

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-notificationConditions_new.adoc[]

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sendTestInformation.adoc[]
====


. Click the **Notification Disabled** switch above to enable DingTalk notifications.