---
title: "Set Up WeCom Notification"
keywords: "Kubernetes, {ks_product-en}, platform settings, notification management, notification settings, set up WeCom notification"
description: "Describes how to set up WeCom notification."
weight: 04
---

// :ks_navigation: **Notification Management > Notification Channels**


This section describes how to set up WeCom notification. After configuration, you can receive notification messages through WeCom chats or chatbots.

== Prerequisites

* **WhizardTelemetry Notification** should have been installed and enabled.

* You should get the access parameters for the WeCom application in advance. For more information, see link:https://developer.work.weixin.qq.com/document/path/90664[WeCom Developer Documentation].

== Steps

. Log in to the {ks_product-en} web console.

. Click the current username in the upper-right corner of the page, and then select **Notification Settings** from the dropdown list.

. On the **Notification Settings** page, under the **WeCom** tab, set the WeCom notification parameters, and then click **OK**.

+
====
// * Server Settings
// +
// --
// [%header,cols="1a,4a"]
// |===
// |Parameter |Description

// |Corp ID
// |Your company's Corp ID on WeCom.

// |Agent ID
// |The Agent ID of the WeCom application.

// |Secret
// |The Secret of the WeCom application.
// |===
// --

* Chat Settings > Recipient Settings
+
--
Set the User ID, Department ID, or Tag ID that will receive notifications. Click **Add** to set multiple IDs.
--

* Chatbot Settings > Chatbot Settings
+
--
Webhook URL: The webhook address of the WeCom group bot.
--

* Chatbot Settings > Recipient Settings
+
--
Set the User ID or user phone number that will receive notifications. Click **Add** to set multiple IDs and phone numbers.
--

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-notificationConditions_new.adoc[]

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sendTestInformation.adoc[]
====

. Click the **Notification Disabled** switch above to enable WeCom notifications.