---
title: "Set Up Slack Notification"
keywords: "Kubernetes, {ks_product-en}, platform settings, notification management, notification settings, set up Slack notification"
description: "Describes how to set up Slack notification."
weight: 05
---


// :ks_navigation: **Notification Management > Notification Channels**


This section describes how to set up Slack notification.


== Prerequisites

* **WhizardTelemetry Notification** should have been installed and enabled.

* You should get the access parameters for the Slack application in advance. For more information, see link:https://api.slack.com/messaging/webhooks#create_a_webhook[Slack Developer Documentation].

== Steps

. Log in to the {ks_product-en} web console.

. Click the current username in the upper-right corner of the page, and then select **Notification Settings** from the dropdown list.

. On the **Notification Settings** page, under the **Slack** tab, set the Slack notification parameters, and then click **OK**.

+
====
// * Server Settings
// +
// --
// Set the token used to access the Slack application.
// --

* Slack Channel Settings
+
--
Set the Slack channels that will receive notifications. Click **Add** to set multiple Slack channels.
--

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-notificationConditions_new.adoc[]

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sendTestInformation.adoc[]
====

. Click the **Notification Disabled** switch above to enable Slack notifications.