---
title: "Set Up Webhook Notification"
keywords: "Kubernetes, {ks_product-en}, platform settings, notification management, notification settings, set up Webhook notification"
description: "Learn how to set up Webhook notification."
weight: 06
---

// :ks_navigation: **Notification Management > Notification Channels**

This section describes how to set up Webhook notification.

== Prerequisites

* **WhizardTelemetry Notification** should have been installed and enabled.

* You should get the access parameters for the Webhook in advance. For more information, please contact your Webhook administrator.

== Steps

. Log in to the {ks_product-en} web console.

. Click the current username in the upper-right corner of the page, and then select **Notification Settings** from the drop-down list.

. On the **Notification Settings** page, under the **Webhook** tab, set the Webhook notification parameters, and then click **OK**.

+
====
* Server Settings
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

|Webhook URL
|The access URL for the Webhook.

|Authentication Type
|The authentication type for the Webhook.

* **No Authentication**: No authentication is required.

* **Bearer Token**: Use a URL Bearer token for authentication. If you choose this type, you need to further set the token used for authentication.

* **Basic Authentication**: Use a username and password for authentication. If you choose this type, you need to further set the username and password used for authentication.

|Skip TLS Verification (Insecure)
|Whether to skip TLS verification when calling the Webhook.
|===
--

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-notificationConditions_new.adoc[]

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sendTestInformation.adoc[]
====

. Click the **Notification Disabled** switch at the top to enable Webhook notification.