---
title: "Upgrade Extensions"
keywords: "Kubernetes, KubeSphere, Upgrade, Extensions"
description: "Learn how to upgrade extensions."
weight: 03
---

This section explains how to upgrade extensions.

Before upgrading the extensions, make sure to update the extension repository to fetch the latest versions. You can update the ks-core extension repository using the following command:

[source,bash]
----
helm -n kubesphere-system upgrade ks-core https://charts.kubesphere.io/main/ks-core-<VERSION>.tgz --set ksExtensionRepository.image=$(curl -s https://api.github.com/repos/kubesphere-extensions/ks-extensions/releases/latest | jq -r '.tag_name')
----

== Prerequisites

You should have the **platform-admin** role on {ks_product-en} platform. For more information, refer to link:../../../05-users-and-roles/01-users/[Users] and link:../../../05-users-and-roles/02-platform-roles/[Platform Roles].

== Steps

. Log in to the {ks_product-en} web console with a user having the **platform-admin** role.
. Click **Extensions Center**.
. Click the name of the installed extension to enter its details page.
. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] below the extension icon and select **Upgrade**.
. In the update dialog, follow the installation process to complete the upgrade.