---
title: "Uninstall Extensions"
keywords: "Kubernetes, KubeSphere, Uninstall, Force Uninstall, Extensions"
description: "Learn how to uninstall extensions."
weight: 04
---

This section explains how to uninstall extensions.

You can uninstall extensions on the extension details page in the Extensions Center.

For multi-cluster environments, when uninstalling, the cluster agent will be uninstalled first, followed by the extension.

== Prerequisites

You should have the **platform-admin** role on {ks_product-en} platform. For more information, refer to link:../../../05-users-and-roles/01-users/[Users] and link:../../../05-users-and-roles/02-platform-roles/[Platform Roles].

== Steps

. Log in to the {ks_product-en} web console with a user having the **platform-admin** role.
. Click **Extensions Center**.
. Click the name of the installed extension to enter its details page.
. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] below the extension icon and select **Uninstall**.
. Enter the extension name, and click **OK** to start uninstallation.


