---
title: "Cluster Monitoring Overview"
description: "This section introduces how to view monitoring information on the cluster overview page."
weight: 01
---

:ks_permission: **Monitoring Viewing**
:ks_navigation: **Overview**

This section introduces how to view monitoring information on the cluster overview page.

ifeval::["{file_output_type}" == "html"]
For other information on the cluster overview page, see link:../../../../../07-cluster-management/02-overview/01-view-cluster-overall-information/[Cluster Overview].
endif::[]

ifeval::["{file_output_type}" == "pdf"]
For other information on the cluster overview page, see the “Overview” chapter of the {ks_product-en} Cluster Management Guide.
endif::[]

== Prerequisites

* {empty}
include::../../../../../_custom-en/clusterManagement/clusterManagement-prer-requiredPermission_new.adoc[]

* **WhizardTelemetry Monitoring** should have been installed and enabled.

== Steps

include::../../../../../_custom-en/clusterManagement/clusterManagement-oper-openClusterPage.adoc[]

+

include::../../../../../../_ks_components-en/oper-navigate.adoc[]

+
--
The **Overview** page provides the following monitoring information:

[%header,cols="1a,4a"]
|===
|Area |Description

|Cluster Quota Statistics
|The CPU quota and memory quota of containers and projects in the current cluster, including quantity request, quantity limit, and total quantity.

|Node Resource Usage
|The total and real-time usage of CPU, memory, and disk for all nodes, as well as the total number of pods allowed to be created in the cluster and the number of pods already created. By default, each node allows a maximum of 110 pods to be created.

|Pods
|The number of various types of pods in the current cluster.

Pod status includes:

include::../../../../../_custom-en/clusterManagement/pods/pods-para-podStatus_overview.adoc[]

Pod QoS (Quality of Service) types include:

include::../../../../../_custom-en/clusterManagement/pods/pods-para-qosTypes.adoc[]

|Kubernetes Status
|The number of API requests per second, API request latency, pod scheduling times, and pod scheduling failure times in the current cluster.

|Resource Usage Ranking
|The top 5 nodes, pods, and projects with the highest resource usage in the current cluster.

* Select nodes, pods, or projects from the dropdown list on the left, and select different sorting criteria from the dropdown list on the right.

* Click image:/images/ks-qkcp/zh/icons/sort-ascending.svg[sort-ascending,18,18]/image:/images/ks-qkcp/zh/icons/sort-descending.svg[sort-descending,18,18] above the list to sort in ascending/descending order.

* Click **View More** below to view the resource usage details of nodes, pods, and projects.
|===
--