---
title: "View Notification Subscription"
description: "Describes how to view notification subscriptions."
weight: 02
---

:ks_navigation: **Notification Management > Notification Subscription**
:ks_permission: **Platform Settings Management**

This section describes how to view notification subscriptions.

== Prerequisites

* {empty}
include::../../../../../_custom-en/platformManagement/platformManagement-prer-requiredPermission_v4.adoc[]

* **WhizardTelemetry Notification** should have been installed and enabled.


== Steps

. Log in to the {ks_product-en} web console with a user who has the pass:a,q[{ks_permission}] permission.
. Click image:/images/ks-qkcp/zh/icons/cogwheel.svg[cogwheel,18,18] in the upper-right corner of the {ks_product-en} web console to enter the **Platform Settings** page.
. Select pass:a,q[{ks_navigation}] in the left navigation pane.
. On the **Notification Subscription** page, under the **Email** tab, view the list of created notification subscriptions.
+
--
The notification subscription list provides the following information:

[%header,cols="1a,4a"]
|===
|Parameter|Description

|Name
|The name of the notification subscription.

|Notification Reception Status
|Whether the notification subscription is enabled.

|Number of Subscription Accounts
|The number of accounts that will receive notifications.

|Creation Time
|The creation time of the notification subscription.
|===

* Click the search box above the list to search for notification subscriptions by name.

include::../../../../../../_ks_components-en/oper-refreshListData.adoc[]

include::../../../../../../_ks_components-en/oper-customizeColumns.adoc[]
--

. Click the name of a notification subscription to view detailed information, such as subscription accounts and filter conditions.