---
title: "Edit Notification Subscription"
description: "Describes how to edit a notification subscription."
weight: 03
---

:ks_navigation: **Notification Management > Notification Subscription**
:ks_permission: **Platform Settings Management**


This section describes how to edit a notification subscription.


== Prerequisites

* {empty}
include::../../../../../_custom-en/platformManagement/platformManagement-prer-requiredPermission_v4.adoc[]

* **WhizardTelemetry Notification** should have been installed and enabled.

== Steps

. Log in to the {ks_product-en} web console with a user who has the pass:a,q[{ks_permission}] permission.
. Click image:/images/ks-qkcp/zh/icons/cogwheel.svg[cogwheel,18,18] in the upper-right corner of the {ks_product-en} web console to enter the **Platform Settings** page.
. Select pass:a,q[{ks_navigation}] in the left navigation pane.
. On the **Notification Subscription** page, under the **Email** tab, view the list of created notification subscriptions.
. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] on the right side of the notification subscription, and then select **Edit Notification Subscription** from the dropdown list.
. On the **Edit Notification Subscription** page, edit the information, and then click **OK**.
+
====
* Basic Information
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

|Alias
|The alias of the notification subscription. The alias can only contain Chinese characters, letters, numbers, and hyphens (-), cannot start or end with a hyphen (-), and can be up to 63 characters long.

|Description
|The description of the notification subscription. The description can contain any characters and can be up to 256 characters long.

|===
--

* Recipient Settings
+
--
Set the email addresses that will receive notifications. Click **Add** to set multiple addresses.
--

* Notification Receipt
+
--
Click the toggle switch to enable or disable the notification subscription.
--

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-notificationConditions_new.adoc[]

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sendTestInformation.adoc[]

====