---
title: "Delete Notification Subscriptions"
description: "Describes how to delete a notification subscription."
weight: 04
---

:ks_navigation: **Notification Management > Notification Subscription**
:ks_permission: **Platform Settings Management**


This section describes how to delete a notification subscription.


== Prerequisites

* {empty}
include::../../../../../_custom-en/platformManagement/platformManagement-prer-requiredPermission_v4.adoc[]

* **WhizardTelemetry Notification** should have been installed and enabled.


== Delete a Single Notification Subscription

. Log in to the {ks_product-en} web console with a user who has the pass:a,q[{ks_permission}] permission.
. Click image:/images/ks-qkcp/zh/icons/cogwheel.svg[cogwheel,18,18] in the upper-right corner of the {ks_product-en} web console to enter the **Platform Settings** page.
. Select pass:a,q[{ks_navigation}] in the left navigation pane.
. On the **Notification Subscription** page, under the **Email** tab, view the list of created notification subscriptions.
. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] on the right side of the notification subscription, and then select **Delete** from the dropdown list.
. In the **Delete Notification Subscription** dialog, enter the name of the notification subscription, and then click **OK**.

== Delete Multiple Notification Subscriptions

. Log in to the {ks_product-en} web console with a user who has the pass:a,q[{ks_permission}] permission.
. Click image:/images/ks-qkcp/zh/icons/cogwheel.svg[cogwheel,18,18] in the upper-right corner of the {ks_product-en} web console to enter the **Platform Settings** page.
. Select pass:a,q[{ks_navigation}] in the left navigation pane.
. On the **Notification Subscription** page, under the **Email** tab, view the list of created notification subscriptions.
. Select the checkbox on the left side of the notification subscriptions you need to delete, and then click **Delete** above the list.
. In the **Delete Multiple Notification Subscriptions** dialog, enter the names of the notification subscriptions, and then click **OK**.
+
--
include::../../../../../_custom-en/note-separateNamesByComma.adoc[]
--