---
title: "Enable Whizard Observability Center"
description: "Describes how to enable the Whizard Observability Center."
weight: 01
---

This section describes how to configure the relevant extensions to enable the Whizard Observability Center.

To use the full functionality of the Whizard Observability Center, you need to install and enable the WhizardTelemetry Platform Service, WhizardTelemetry Monitoring, and WhizardTelemetry Alerting extensions, and perform the following configurations.

== Prerequisites

* You should have the **platform-admin** role on the {ks_product-en} platform. For more information, see link:../../../../05-users-and-roles/01-users/[Users] and link:../../../../05-users-and-roles/02-platform-roles/[Platform Roles].

* The **WhizardTelemetry Platform Service**, **WhizardTelemetry Monitoring**, and **WhizardTelemetry Alerting** extensions are installed.

// * The license for the Distributed Cloud Observability Center has been imported on the **Platform Settings > License** page. Otherwise, the entry for the Whizard Observability Center will not be visible.

== Steps

. Log in to the {ks_product-en} web console with a user who has the **platform-admin** role.
. Click **Extensions Center**.
. Click the name of the installed extension to enter the details page.
. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] below the icon and select **Extension Config**.
+
--
**WhizardTelemetry Platform Service**

Set the `whizard-telemetry.config.observability.enabled` parameter in the configuration file to `true`, and then click **OK**.

[,yaml]
----
whizard-telemetry:
  config:
    observability:
      enabled: true
      endpoint: "http://query-frontend-whizard-operated.kubesphere-monitoring-system.svc:10902"
----

**WhizardTelemetry Monitoring**

Modify the following part of the configuration file, and then click **OK**.

[,yaml]
----
whizard-monitoring-helper:
  whizardHelper:
    enabled: true   ## set true to enable whizard

whizard:
  enabled: true  

frontend:
  enabled: true

whizardAgentProxy:
  enabled: true

whizard-agent-proxy:
  config:
    gatewayUrl: "http://172.31.73.206:30990"   ## set whizard gateway url，default is http://{host_cluster_node_ip}:30990

kube-prometheus-stack:
  prometheus:
    agentMode: true    # agentMode need to be set to true when enable whizard
----

**WhizardTelemetry Alerting**

Ensure that `global.rules.distributionMode` is set to `None`.

[,yaml]
----
global:
  rules:
    distributionMode: None
----
--

. After editing, click image:/images/ks-qkcp/zh/icons/grid.svg[grid,18,18] on the top navigation bar to find the **Whizard Observability Center** icon.
+
--
[.admon.note,cols="a"]
|===
|Note

|
The enabling process may take some time, please wait for it to complete.
|===
--