---
title: "Set Authorization Rules"
description: "Learn how to set authorization rules for storage classes."
weight: 01
---

:ks_permission: **Storage Class Accessors Management**
:ks_navigation: **Storage > Storage Classes**


This section describes how to set authorization rules for storage classes.

After setting and enabling the authorization rules, users can only use the storage class in specific projects and workspaces.

== Prerequisites

* **KubeSphere Storage** should have been installed and enabled.

* {empty}
include::../../../../_custom-en/clusterManagement/clusterManagement-prer-requiredPermission_new.adoc[]

== Steps

include::../../../../_custom-en/clusterManagement/clusterManagement-oper-openClusterPage.adoc[]

+

include::../../../../../_ks_components-en/oper-navigate.adoc[]

+

include::../../../../_custom-en/clusterManagement/storageClasses/systemClasses-oper-openDetailsPage.adoc[]

+

. In the upper-left corner of the details page, select **More > Set Authorization Rules**.

. In the **Set Authorization Rules** dialog, click the **Disabled** button on the right side of the page to enable the authorization rules.
+
--
// Note
include::../../../../../_ks_components-en/admonitions/note.adoc[]

To disable the authorization rules, click **Enabled** on the right side of the page.

include::../../../../../_ks_components-en/admonitions/admonEnd.adoc[]
--

. In the **Authorization Rules** setting area, set the specific projects and workspaces where the storage class can be used.

. After setting, click **OK**.