---
title: "Log in to Jenkins Dashboard"
keywords: "Kubernetes, {ks_product-en}, DevOps project, Using DevOps, Access Jenkins"
description: "Introduces how to log in to the Jenkins dashboard."
weight: 07
---

Jenkins dashboard is installed by default when you install DevOps.

== Prerequisites

{ks_product-en} platform needs to have the **DevOps** extension installed and enabled.

== Steps

. Check the service corresponding to the Jenkins dashboard, then refer to link:../../../../../02-quickstart/08-access-a-service/[Access a Service] to access Jenkins dashboard.
+
--
[source,bash]
----
kubectl -n kubesphere-devops-system get svc devops-jenkins
----
--

. Get the username and password for Jenkins admin.
+
--
[source,bash]
----
kubectl -n kubesphere-devops-system get secret devops-jenkins -o yaml
----

Sample output:
[source,yaml]
----
data:
  jenkins-admin-password: aXMxZno1Z3lnQWFTaGRIU2EwUDZkbg==
  jenkins-admin-token: MTE5NTQ4NDY3MTE4MDQ4ODAzMDI1MTc3MDk1OTUwNTM2MQ==
  jenkins-admin-user: YWRtaW4=
----

Decode the base64 encoded `jenkins-admin-user` and `jenkins-admin-password` to get the username and password for Jenkins admin.
--

. Use the obtained username and password to log in to Jenkins dashboard.

[.admon.note,cols="a"]
|===
|Note

|
To log in to Jenkins dashboard through LDAP or OpenID Connect, please refer to the instructions on the details page of DevOps extension in Extensions Center.
|===
