---
title: "View Network Policy Details"
keywords: "Kubernetes, {ks_product-en}, cluster management, network, network policy, view network policy details"
description: "Introduce how to view network policy details."
weight: 03
---

:ks_permission: **Cluster Network Resource Viewing**
:ks_navigation: **Network > Network Policies**


This section introduces how to view network policy details.


== Prerequisites

* {empty}
include::../../../../_custom-en/clusterManagement/clusterManagement-prer-requiredPermission_new.adoc[]

* **KubeSphere Network** should have been installed and enabled.


== Steps

include::../../../../_custom-en/clusterManagement/clusterManagement-oper-openClusterPage.adoc[]

+

include::../../../../../_ks_components-en/oper-navigate.adoc[]

+

. Click the name of a network policy in the network policy list to open its details page.

. On the network policy details page, view the resource attributes of the network policy in the **Attributes** area on the left.
+
--
[options="header",cols="1a,4a"]
|===
|Parameter |Description

|Cluster
|The cluster to which the network policy belongs.

|Project
|The project to which the network policy belongs.

|Creation Time
|The creation time of the network policy.

|Creator
|The user who created the network policy.
|===
--

. On the network policy details page, click the **Egress Rules** tab on the right to view the egress rules of the network policy.
+
--
Egress rules are used to restrict pods to access only specific pods or network segments.

[%header,cols="1a,4a"]
|===

|Parameter |Description

|Target
|Information about the pods to which the rule applies.

* **Project**: The project to which the rule belongs. Rules in a network policy only apply to pods in the project to which the network policy belongs.

* **Labels**: The labels of the pods to which the rule applies. If no labels are set, the rule applies to all pods in the project to which the network policy belongs.


|Destination
|Information about other pods or network segments that the target pods can access.

* **Project**: The project to which the other pods belong that the target pods can access.
* **Labels**: The labels of the other pods that the target pods can access. If no labels are set, the target pods can access all pods in the project.
* **CIDR**: The network segment that the target pods can access.
* **Ports**: The ports of the other pods or network segments that the target pods can access. If no ports are set, the target pods can access all ports of the other pods or network segments.
|===
--

. On the network policy details page, click the **Ingress Rules** tab on the right to view the ingress rules of the network policy.
+
--
Ingress rules are used to restrict pods to be accessed only by specific pods or network segments.

[%header,cols="1a,4a"]
|===
|Parameter |Description

|Target
|
include::../../../../_custom-en/clusterManagement/networkPolicies/networkPolicies-para-target.adoc[]

|Destination
|Information about other pods or network segments that can access the target pods.

* **Project**: The project to which the other pods belong that can access the target pods.
* **Labels**: The labels of the other pods that can access the target pods. If no labels are set, all pods in the project can access the target pods.
* **CIDR**: The network segment that can access the target pods.
* **Ports**: The ports of the target pods that can be accessed by other pods or network segments. If no ports are set, all ports of the target pods can be accessed by other pods or network segments.
|===
--