---
title: "Use the Audit Log Query Tool"
keywords: "Kubernetes, {ks_product-en}, cluster management, toolbox, query audit logs"
description: "This section introduces how to use the audit log query tool."
weight: 01
---

This section introduces how to query audit logs.

Audit logs: Records of requests received by the KubeSphere API server, i.e., user behaviors on the {ks_product-en} platform.

== Prerequisites

* You should have resource viewing permissions for the platform, cluster, workspace, or project to view audit logs within a specific scope.

* **WhizardTelemetry Auditing** should have been installed and enabled.

== Enable Auditing

To get audit log data, you need to enable Kubernetes and KubeSphere auditing, i.e., enable audit log collection.

=== Enable Kubernetes Auditing

. Create an audit directory on the master node of the cluster.
+
[,bash]
----
mkdir /etc/kubernetes/audit
----

. Create a policy file.
+
--
[,bash]
----
vi /etc/kubernetes/audit/audit-policy.yaml
----

[,yaml]
----
apiVersion: audit.k8s.io/v1 
kind: Policy
rules:
- level: Metadata
----
--

. Edit the `kube-apiserver.yaml` file and add the following content.
+
--
[,bash]
----
vi /etc/kubernetes/manifests/kube-apiserver.yaml
----

[,yaml]
----
  spec:
    containers:
      - command:
          - kube-apiserver
          - --audit-policy-file=/etc/kubernetes/audit/audit-policy.yaml
          - --audit-log-path=/etc/kubernetes/audit/audit.log
          - --audit-log-maxbackup=10
          - --audit-log-maxsize=100
        volumeMounts:
          - mountPath: /etc/kubernetes/audit
            name: audit
    volumes:
      - hostPath:
          path: /etc/kubernetes/audit
          type: DirectoryOrCreate
        name: audit
----
--

=== Enable KubeSphere Auditing

Edit the `values.yaml` file in the helm chart package of KubeSphere Core (ks-core).

[,yaml]
----
auditing:
  enable: true
  auditLevel: Metadata
  logOptions:
    path: /etc/audit/audit.log

apiserver: 
  extraVolumeMounts:
    - mountPath: /etc/audit
      name: audit
  extraVolumes:
    - hostPath:
        path: /etc/kubesphere/audit
        type: DirectoryOrCreate
      name: audit
----

== Query Audit Logs

. Log in to the {ks_product-en} web console with a user who has the relevant resource viewing permissions.

. Hover the cursor over image:/images/ks-qkcp/zh/icons/hammer.svg[hammer,18,18] at the bottom right of the page, then select **Audit Log Search** from the menu.

. In the pop-up dialog, set the search conditions to query logs.
+
--
* If there are multiple clusters, click the **Cluster** dropdown list to query logs in a specific cluster.

* Click the search box, set the search conditions, then press **Enter** to view logs that meet specific conditions. You can set multiple search conditions at the same time.

* On the query results page, you can view the time distribution chart of the logs. Click the histogram to switch to the log list for that time period. Click image:/images/ks-qkcp/zh/icons/start-dark.svg[start-dark,18,18]/image:/images/ks-qkcp/zh/icons/stop-dark-white.svg[stop-dark-white,18,18] to start/stop real-time data refresh, click the **Refresh Rate** time to select the data refresh frequency.

* Click image:/images/ks-qkcp/zh/icons/cogwheel.svg[cogwheel,18,18] in the upper right corner of the query results list to customize the information displayed in the list.

* Click on a log entry in the query results to view the detailed information of the log.
--