---
title: "Edit Cluster Information"
linkTitle: "Edit Cluster Information"
keywords: "Kubernetes, KubeSphere, Multi-Cluster Management, Cluster, Edit Cluster Information"
description: "Learn how to edit cluster information."
weight: 03
---


:ks_menu: **Cluster Management**
:ks_permission: **Cluster Management**


This section explains how to edit cluster information.

You can edit the identifier, provider, and description of the cluster. KubeSphere does not support editing the name of an already added cluster.

== Prerequisites

include::../../../../_custom-en/platformManagement/platformManagement-prer-requiredPermission_v4.adoc[]


== Steps

include::../../../../_custom-en/platformManagement/platformManagement-oper-logIn.adoc[]

. Click **Cluster Management**.

. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] on the right of the cluster you want to edit, then choose **Edit Information** from the dropdown list.

. In the **Edit Information** dialog, set the identifier, provider and description for the cluster, then click **OK**.
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

|Identifier
|A label used to identify the purpose of the cluster.

| Provider
| The provider of the cluster. Select the provider from the dropdown list.

| Description
| Information describing the cluster. The description can contain any characters and has a maximum length of 256 characters.
|===
--
