---
title: "Update kubeconfig"
linkTitle: "Update kubeconfig"
keywords: "Kubernetes, KubeSphere, Multi-Cluster Management, Cluster, Update kubeconfig"
description: "Learn how to update the kubeconfig information of member clusters."
weight: 05
---


:ks_menu: **Cluster Management**
:ks_permission: **Cluster Management**


This section explains how to update the kubeconfig information of member clusters.

After adding member clusters on the {ks_product-en} platform, if there are changes in the access information of the member clusters, you need to update the kubeconfig of the member clusters.

// Note
include::../../../../../_ks_components-en/admonitions/note.adoc[]

KubeSphere only supports updating the kubeconfig information of clusters added through direct connections and does not support updating the kubeconfig information of clusters added through agent connections.

include::../../../../../_ks_components-en/admonitions/admonEnd.adoc[]


== Prerequisites

include::../../../../_custom-en/platformManagement/platformManagement-prer-requiredPermission_v4.adoc[]



== Steps

include::../../../../_custom-en/platformManagement/platformManagement-oper-logIn.adoc[]

. Click **Cluster Management**.

. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] on the right side of the cluster you want to edit, then select **Update kubeconfig** from the dropdown list.

. In the **Update kubeconfig** dialog, enter the kubeconfig information and then click **Update**.
+
--
// Tip
include::../../../../../_ks_components-en/admonitions/tip.adoc[]

You can click image:/images/ks-qkcp/zh/icons/upload-dark-white.svg[upload-dark-white,18,18] to upload kubeconfig files from your local machine.

include::../../../../../_ks_components-en/admonitions/admonEnd.adoc[]

The {ks_product-en} web console of the host cluster will use the new kubeconfig information to connect to the member clusters.
--