---
title: "Edit Workspace Information"
linkTitle: "Edit Workspace Information"
keywords: "Kubernetes, KubeSphere, Access Control, Workspace, Edit Workspace Information"
description: "Learn how to edit workspace information."
weight: 03
---

:ks_permission: **Workspace Management**

This section explains how to edit workspace information.

You can edit the alias and description of a workspace. KubeSphere does not support editing the name of an already created workspace.

== Prerequisites

include::../../../_custom-en/platformManagement/platformManagement-prer-requiredPermission_v4.adoc[]


== Steps

include::../../../_custom-en/platformManagement/platformManagement-oper-logIn.adoc[]

. Click **Workspace Management**.

. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] on the right of the workspace you want to edit, then choose **Edit Information** from the dropdown list.

. In the **Edit Information** dialog, set the alias and description for the workspace, then click **OK**.
+
--
[%header,cols="1a,4a"]
|===
| Parameter | Description

| Alias
| The alias of the workspace. The alias can contain any characters, with a maximum length of 63 characters.

| Description
| The description of the workspace. The description can contain any characters, with a maximum length of 256 characters.
|===
--
