---
title: "Create Composed Apps"
keywords: "Kubernetes, {ks_product-en}, Project Management, Apps, Create Composed App"
description: "Describes how to create a composed app."
weight: 03
---

:ks_permission: **Service Mesh Management**
:ks_navigation: **Service Mesh > Composed Apps**

This section describes how to create a composed app.

include::../../../../_custom-en/projectManagement/apps/apps-compose-description.adoc[]

== Prerequisites

* {empty}
include::../../../../_custom-en/projectManagement/projectManagement-prer-requiredPermission_new.adoc[]

* **KubeSphere Service Mesh** should have been installed and enabled.

== Steps

include::../../../../_custom-en/projectManagement/projectManagement-oper-openProjectPage.adoc[]

+

include::../../../../../_ks_components-en/oper-navigate.adoc[]

+

include::../../../../../_ks_components-en/oper-clickCreate.adoc[]

. On the **Basic Information** tab, set the basic information of the app, then click **Next**.
+
--
include::../../../../_custom-en/projectManagement/apps/apps-basic-para.adoc[]
--

. On the **Service Settings** tab, click **Create Service**, select **Stateful Service** or **Stateless Service** to create services for the app, then click **Next**.
+
--
include::../../../../_custom-en/clusterManagement/services/services-para-statelessStatefulExternal.adoc[]

ifeval::["{file_output_type}" == "html"]
For parameter settings of **Stateful Service** and **Stateless Service**, see link:../../../../09-project-management/03-application-workloads/02-services/01-create-a-service/01-create-a-stateful-or-stateless-service/#_parameter_description[Create a Stateful or Stateless Service].
endif::[]

ifeval::["{file_output_type}" == "pdf"]
For parameter settings of **Stateful Service** and **Stateless Service**, see the "Create a Stateful or Stateless Service" section in the {ks_product-en} Project Management Guide.
endif::[]
--

. On the **Ingress Settings** tab, click **Add Routing Rule** to create routing rules for the app, then click **Create**.
+
--
include::../../../../_custom-en/clusterManagement/routes/routes-para-routingRules.adoc[]

The app will be displayed on the **Composed Apps** page after it is created.
--