---
title: "Delete Microservice Configuration"
keywords: "Kubernetes, {ks_product-en}, project management, Spring Cloud, delete microservice configuration"
description: "Learn how to delete a microservice configuration."
weight: 07
---

:ks_permission: **Spring Cloud Microservices Management**
:ks_navigation: **Spring Cloud > Microservice Configurations**

This section describes how to delete a microservice configuration.

== Prerequisites

* **KubeSphere Spring Cloud** should have been installed and enabled.

* {empty}
include::../../../../_custom-en/projectManagement/projectManagement-prer-requiredPermission_new.adoc[]

== Delete a Single Microservice Configuration

include::../../../../_custom-en/projectManagement/projectManagement-oper-openProjectPage.adoc[]

+

include::../../../../../_ks_components-en/oper-navigate.adoc[]

+

. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] on the right side of the microservice configuration you want to delete, and then select **Delete** from the drop-down list.

. In the **Delete Microservice Configuration** dialog, enter the name of the microservice configuration, and then click **OK**.

== Delete Multiple Microservice Configurations

include::../../../../_custom-en/projectManagement/projectManagement-oper-openProjectPage.adoc[]

+

include::../../../../../_ks_components-en/oper-navigate.adoc[]

+

. Select the checkboxes on the left side of the microservice configurations you want to delete, and then click **Delete** at the top of the list.

. In the **Delete Multiple Microservice Configurations** dialog, enter the names of the microservice configurations, and then click **OK**.
+
--
include::../../../../_custom-en/note-separateNamesByComma.adoc[]
--