---
title: "Configure Cluster Agent"
keywords: "Kubernetes, KubeSphere, Set, Configure, Cluster Agent"
description: "Learn how to configure the cluster agent."
weight: 02
---

This section explains how to configure the cluster agent.

In addition to configuring the cluster agent during extension installation, you can also modify the configuration of the cluster agent on the extension details page.

== Prerequisites

* You need to have the **platform-admin** role on {ks_product-en} platform. For more information, refer to link:../../../05-users-and-roles/01-users/[Users] and link:../../../05-users-and-roles/02-platform-roles/[Platform Roles].
* You have successfully installed an extension configured with a cluster agent.

== Configure Cluster Agent

. Log in to the {ks_product-en} web console with a user having the **platform-admin** role.
. Click **Extensions Center**.
. Click the name of the installed extension to enter its details page.
. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] below the extension icon and select **Cluster Agent Configs**.
. Choose clusters and set configurations for them.
. Click **OK**.