---
title: "Change User Password"
linkTitle: "Change User Password"
keywords: "Kubernetes, KubeSphere, Access Control, User, Change User Password"
description: "Learn how to change user passwords."
weight: 06
---

:ks_menu: **Users and Roles**
:ks_navigation: **Users**
:ks_permission: **User Management**

This section explains how to change user passwords.

== Change Password for the Current User

. Log in to the {ks_product-en} web console.

. Click the current username in the top-right corner, then select **User Settings** from the drop-down list.

. Click the **Password Settings** tab to change the password for the current user.
+
The password must contain at least one number, one lowercase letter, one uppercase letter, and one special character (~!@#$%^&*()-_=+\|[{}];:'",<.>/? or space). The length must be 8 to 64 characters.

== Change Password for Other Users

. Log in to the {ks_product-en} web console with a user who has the pass:a,q[{ks_permission}] permission.
. Click pass:a,q[{ks_menu}].
. Click pass:a,q[{ks_navigation}] in the left navigation pane.
. Click the name of a user to open its details page.
. In the top-left corner of the user details page, select **More > Change Password**.
. In the **Change Password** dialog, set a new password and re-enter it, then click **OK**.
+
The password must contain at least one number, one lowercase letter, one uppercase letter, and one special character (~!@#$%^&*()-_=+\|[{}];:'",<.>/? or space). The length must be 8 to 64 characters.