---
title: "Enable and Disable Users"
linkTitle: "Enable and Disable Users"
keywords: "Kubernetes, KubeSphere, Access Control, Users, Enable and Disable Users"
description: "Explain how to enable and disable users."
weight: 09
---

:ks_menu: **Users and Roles**
:ks_navigation: **Users**
:ks_permission: **User Management**

This section explains how to enable and disable users.

After a user is disabled, it will be unable to log in to the {ks_product-en} web console.

== Prerequisites

You need to have pass:a,q[{ks_permission}] permission on the {ks_product-en} platform. For more information, see link:../../01-users/[Users] and link:../../02-platform-roles/[Platform Roles].

== Enable and Disable a Single User

. Log in to the {ks_product-en} web console with a user who has the pass:a,q[{ks_permission}] permission.
. Click pass:a,q[{ks_menu}].
. Click pass:a,q[{ks_navigation}] in the left navigation pane.
. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] to the right of a user, and then select **Enable** or **Disable** from the dropdown list.

== Batch Enable and Disable Users

. Log in to the {ks_product-en} web console with a user who has the pass:a,q[{ks_permission}] permission.
. Click pass:a,q[{ks_menu}].
. Click pass:a,q[{ks_navigation}] in the left navigation pane.
. Check the boxes next to the users you want, and then click **Enable** or **Disable** above the list.
