---
title: "Delete Users"
linkTitle: "Delete Users"
keywords: "Kubernetes, KubeSphere, Access Control, User, Delete User"
description: "Learn how to delete users."
weight: 10
---

:ks_menu: **Users and Roles**
:ks_navigation: **Users**
:ks_permission: **User Management**

This section explains how to delete users.

== Prerequisites

You need to have pass:a,q[{ks_permission}] permissions on the {ks_product-en} platform. For more information, please refer to link:../../01-users/[Users] and link:../../02-platform-roles/[Platform Roles].

== Delete a Single User

. Log in to the {ks_product-en} web console with a user who has pass:a,q[{ks_permission}] permissions.
. Click pass:a,q[{ks_menu}].
. Click pass:a,q[{ks_navigation}] in the left navigation pane.
. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] next to the user you want to delete, then choose **Delete** from the drop-down list.
. In the **Delete User** dialog, enter the user's name, then click **OK**.

== Delete Multiple Users

. Log in to the {ks_product-en} web console with a user who has pass:a,q[{ks_permission}] permissions.
. Click pass:a,q[{ks_menu}].
. Click pass:a,q[{ks_navigation}] in the left navigation pane.
. Check the boxes next to the users you want to delete, then click **Delete** above the list.
. In the **Delete Multiple Users** dialog, enter the names of the users, then click **OK**.
+
include::../../../../_ks_components-en/admonitions/note.adoc[]

Please use a comma (,) or space to separate multiple names.

include::../../../../_ks_components-en/admonitions/admonEnd.adoc[]

