---
title: "View App Details"
description: "Describes how to view app details."
weight: 02
---

:ks_permission: **App Store Management**
:ks_navigation: **Deployment Management**

This section describes how to view the details of a deployed app.

== Prerequisites

* {empty}
include::../../../../../_custom-en/platformManagement/platformManagement-prer-requiredPermission_v4.adoc[]

* **KubeSphere App Store Management** should have been installed and enabled.

== Steps

include::../../../../../_custom-en/platformManagement/platformManagement-oper-logIn.adoc[]

. Click image:/images/ks-qkcp/zh/icons/grid.svg[grid,18,18] in the upper-right corner and select **App Store Management**.

+

include::../../../../../../_ks_components-en/oper-navigate.adoc[]

+

. On the **Deployment Management** page, click the name of an app to open its details page.

. On the app details page, view the resource attributes of the app in the **Attributes** area on the left.
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

|Cluster
|The cluster to which the app belongs.

|Project
|The project to which the app belongs.

include::../../../../../_custom-en/projectManagement/apps/apps-para-status_v4.adoc[]

|Application
|The app template used by the app.

include::../../../../../_custom-en/projectManagement/apps/apps-para-details2.adoc[]
|===
--

+

include::../../../../../_custom-en/projectManagement/apps/apps-oper-viewResourceStatus_v4.adoc[]

+

. On the right side of the app details page, click **App Template** to view the information of the app template.
+
--
* Click **App Description** to view the introduction of the app template.

* Click **Chart Files** to view the files in the Helm Chart package. On the right side of **Chart Files**, click the dropdown list to select the file you want to view. Click image:/images/ks-qkcp/zh/icons/download-dark-white.svg[download,18,18] to download the file to your local machine.
--

. On the right side of the app details page, click **App Settings** to view the settings information of the app.
+
--
// Note
include::../../../../../../_ks_components-en/admonitions/note.adoc[]

The default settings of the app are saved in the **values.yaml** file in the Helm Chart package. The **App Settings** page displays the settings customized by the user during the app installation.

include::../../../../../../_ks_components-en/admonitions/admonEnd.adoc[]
--