---
title: "Deploy App from App Templates"
keywords: "Kubernetes, {ks_product-en}, Project Management, Apps, Install App from App Template"
description: "Describes how to install an app from an app template."
weight: 10
---

:ks_permission: **App Store Management**
:ks_navigation: **Deployment Management**

This section describes how to deploy an app from an app template on the App Store Management page.

== Prerequisites

* {empty}
include::../../../../../_custom-en/platformManagement/platformManagement-prer-requiredPermission_v4.adoc[]

* **KubeSphere App Store Management** should have been installed and enabled.

== Steps

include::../../../../../_custom-en/platformManagement/platformManagement-oper-logIn.adoc[]

. Click image:/images/ks-qkcp/zh/icons/grid.svg[grid,18,18] in the upper-right corner and select **App Store Management**.

+

include::../../../../../../_ks_components-en/oper-navigate.adoc[]

+

include::../../../../../../_ks_components-en/oper-clickCreate.adoc[]

+

. In the **Create App** dialog, click **From App Template**.

. On the **App Template** page, click the **Current Workspace** dropdown list and select **Current Workspace** or an app repository.

. Click the app template you want to use, then click **Install**.
+
--
// Note
include::../../../../../../_ks_components-en/admonitions/note.adoc[]

App templates are created by workspace members with relevant permissions, and app repositories are created by App Store administrators.
For more information, see link:../../../02-app-management/01-app-templates/01-create-an-app-template/[Create an App Template] and link:../../../03-app-store-management/04-app-repositories/01-add-an-app-repository/[Add an App Repository].

include::../../../../../../_ks_components-en/admonitions/admonEnd.adoc[]
--

+

include::../../../../../_custom-en/projectManagement/apps/apps-oper-installApp.adoc[]
+
--
// Note
include::../../../../../../_ks_components-en/admonitions/note.adoc[]

For more information about app parameters, please contact the relevant workspace members or the app provider.

include::../../../../../../_ks_components-en/admonitions/admonEnd.adoc[]

The app will be displayed in the app list after it is created.
--