---
title: "WhizardTelemetry 告警"
keywords: "Kubernetes, {ks_product}, 集群管理, 监控告警"
description: "介绍如何使用“WhizardTelemetry 告警”扩展组件。"
weight: 06
layout: "second"
---

本节介绍如何使用“WhizardTelemetry 告警”扩展组件。

WhizardTelemetry 告警基于 KubeSphere 采集的监控数据，可针对不同资源类型和监控指标，提供平台、集群及项目视角的告警及告警规则管理功能。

安装“WhizardTelemetry 告警”扩展组件后，集群和项目左侧导航栏的**监控告警**菜单下将显⽰**告警**和**规则组**选项。

//attention
[.admon.attention,cols="a"]
|===
| 注意

|
- WhizardTelemetry 告警依赖 WhizardTelemetry 平台服务和 WhizardTelemetry 监控，因此在安装 WhizardTelemetry 告警之前必须先安装 WhizardTelemetry 平台服务和 WhizardTelemetry 监控两个扩展组件，否则告警相关功能无法正常使用！

- 为了及时收到系统告警消息，建议同时安装 WhizardTelemetry 通知扩展组件。
|===

**配置说明：**

[.admon.attention,cols="a"]
|===
|注意

|
如果在安装 WhizardTelemetry 告警之后，对 WhizardTelemetry 监控是否启用 Whizard 可观测中心进行了变更，请按以下说明更新 WhizardTelemetry 告警的配置。
|===

* 当 **WhizardTelemetry 监控**扩展组件未启用 Whizard 可观测中心时：

. 安装 **WhizardTelemetry 告警**扩展组件时，设置 `global.rules.distributionMode` 为 `Member`。

. 配置 `agent.ruler.alertmanagersUrl` 为 alertmanager-proxy 服务地址（该服务由 WhizardTelemetry 通知提供，安装在 host 集群，默认可在 http://<host-node-ip>:31093 访问）。
+
--
[,yaml]
----
global:
  rules:
    distributionMode: Member

agent:
  ruler:
    alertmanagersUrl:
    - 'http://<host node ip>:31093'
----

[.admon.note,cols="a"]
|===
|说明

|
如果未启用 WhizardTelemetry 通知，希望将告警发送到外部 alertmanager 时，请将 `agent.ruler.alertmanagersUrl` 配置为外部服务地址。
|===
--

* 当 **WhizardTelemetry 监控**扩展组件已启用 Whizard 可观测中心时：
+
====
安装 **WhizardTelemetry 告警**扩展组件时，保持 `global.rules.distributionMode` 为 `None`。

[,yaml]
----
global:
  rules:
    distributionMode: None
----

在该场景下，告警默认直接推送到 alertmanager 服务（该服务由 WhizardTelemetry 通知提供，安装在 host 集群）。保持如下默认配置即可。

[,yaml]
----
extension:
  ruler:
    alertmanagersUrl:
    - 'dnssrv+http://whizard-notification-alertmanager-headless.kubesphere-monitoring-system.svc:9093'
----

[.admon.note,cols="a"]
|===
|说明

|
如果未启用 WhizardTelemetry 通知，希望将告警发送到外部 alertmanager 时，请将 `extension.ruler.alertmanagersUrl` 配置为外部服务地址。
|===
====