---
title: "WhizardTelemetry 告警管理"
keywords: "Kubernetes, {ks_product}, 集群管理, 监控告警"
description: "介绍如何监控集群状态、应用资源和告警，以及管理告警规则组和自定监控面板。"
weight: 06
---

本节介绍如何使用“WhizardTelemetry 告警管理”扩展组件。

WhizardTelemetry 告警管理基于 KubeSphere 采集的监控数据，可针对不同资源类型和监控指标，提供平台、集群及项目视角的告警及告警规则管理功能。

安装“WhizardTelemetry 告警管理”扩展组件后，集群和项目左侧导航栏的**监控告警**菜单下将显⽰**告警**和**规则组**选项。

//attention
[.admon.attention,cols="a"]
|===
| 注意

|
- WhizardTelemetry 告警管理依赖 WhizardTelemetry 平台服务和 WhizardTelemetry 监控，因此在安装 WhizardTelemetry 告警管理之前必须先安装 WhizardTelemetry 平台服务和 WhizardTelemetry 监控两个扩展组件，否则告警相关功能无法正常使用！

- 为了及时收到系统告警消息，建议同时安装 WhizardTelemetry 通知管理扩展组件。
|===

**配置说明：**

* 当 **WhizardTelemetry 监控**扩展组件未启用 Whizard 可观测中心时：

. 安装 **WhizardTelemetry 告警管理**扩展组件时，保持 `global.rules.distributionMode` 为 Member。
. 若使用 **WhizardTelemetry 通知管理**扩展组件发送告警消息，需将 WhizardTelemetry 告警管理的 `agent.ruler.alertmanagersUrl` 配置为 WhizardTelemetry 通知管理的 `alertmanager-proxy` 服务，该服务安装在 host 集群，以 NodePort 形式（默认 31093）暴露。
+
[,yaml]
----
global:
  rules:
    distributionMode: Member

agent:
  ruler:
    alertmanagersUrl:
    - 'http://<host>:<port>'
----


* 当 **WhizardTelemetry 监控**扩展组件已启用 Whizard 可观测中心时：

. 安装 **WhizardTelemetry 告警管理**扩展组件时，保持 `global.rules.distributionMode` 为 None。
. 若使用 **WhizardTelemetry 通知管理**扩展组件发送告警消息，需将 WhizardTelemetry 告警管理的 `extension.ruler.alertmanagersUrl` 配置为 WhizardTelemetry 通知管理的 `alertmanager` 服务（按如下配置即可）。
+
[,yaml]
----
global:
  rules:
    distributionMode: None

extension:
  ruler:
    alertmanagersUrl:
    - 'dnssrv+http://whizard-notification-alertmanager-headless.kubesphere-monitoring-system.svc:9093'
----
