---
title: "View Multi-cluster Monitoring Data"
keywords: "Kubernetes, {ks_product-en}, platform management, Whizard Observability Center, view multi-cluster monitoring data"
description: "Describes how to view multi-cluster monitoring data."
weight: 01
---


This section describes how to view monitoring data across multiple clusters.


== Prerequisites

* You should have the **platform-admin** role on the {ks_product-en} platform. For more information, see link:../../../../../05-users-and-roles/01-users/[Users] and link:../../../../../05-users-and-roles/02-platform-roles/[Platform Roles].

* The host cluster and member clusters that need monitoring must have the Whizard Observability Center enabled.
+
--
// Note
include::../../../../../../_ks_components-en/admonitions/note.adoc[]

If the member cluster does not have the Whizard Observability Center enabled, the Whizard Observability Center will not be able to retrieve data from the member cluster.

include::../../../../../../_ks_components-en/admonitions/admonEnd.adoc[]
--


== Steps

include::../../../../../_custom-en/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

+

. Click image:/images/ks-qkcp/zh/icons/grid.svg[grid,18,18] in the upper-right corner of the page and click **Whizard Observability Center**.

+
--
The **Overview** page of the Whizard Observability Center displays monitoring information for all clusters.

[%header,cols="1a,4a"]
|===
|Area |Description

|Number of Created Resources
|Displays the number of all monitored clusters, nodes, projects, pods, deployments, StatefulSets, DaemonSets, Jobs, CronJobs, persistent volume claims, services, and Ingresses.

|Resource Usage
|Displays the CPU, memory, and disk usage of all nodes in all monitored clusters, as well as the percentage of the number of created pods to the maximum number of pods that can be created. By default, each node can create up to 110 pods.

For CPU and memory, hover over image:/images/ks-qkcp/zh/icons/eye.svg[eye,18,18] to view the reserved and limit resources allocated to containers and projects.

// |Cluster Members and Cluster Roles
// |Displays the number of cluster members and cluster roles in all monitored clusters.

|Global Alerts
|Displays the number of alerts generated by global alerting rule groups and the latest alert messages. Alerts displayed here do not include those generated by alerting rule groups of clusters and projects. Global alerting rule groups are managed by platform administrators in the Whizard Observability Center.

Alert severity include **Info, Warning, Error, and Critical**.

Alert status includes:

include::../../../../../_custom-en/clusterManagement/alerts/alerts-para-alertingStatus.adoc[]

|Pods
|Displays the number of various types of pods in all monitored clusters.

Pod status includes:

include::../../../../../_custom-en/clusterManagement/pods/pods-para-podStatus_overview.adoc[]

Pod QoS (Quality of Service) types include:

include::../../../../../_custom-en/clusterManagement/pods/pods-para-qosTypes.adoc[]
|===
--

. In the upper-right corner of the page, click **Select Cluster** and select the cluster you want to monitor. The overview page will display monitoring information for the selected cluster.

. Click **Collapse Cluster List/Expand Cluster List** to hide or show the cluster list on the right.
+
--
* Click the cluster name in the cluster list to enter the overview page of that cluster.

* Click image:/images/ks-qkcp/zh/icons/row.svg[row,18,18] and image:/images/ks-qkcp/zh/icons/list_view.svg[list_view,18,18] to view cluster information in list or thumbnail.
--