---
title: "View Resource Usage Rankings"
keywords: "Kubernetes, {ks_product-en}, multi-cluster, Whizard Observability Center, resource usage rankings"
description: "Describes how to view resource usage rankings."
weight: 03
---

:ks_navigation: **Resource Monitoring > Resource Ranking**


This section describes how to view resource usage rankings, i.e., the clusters, nodes, projects, and pods with the highest resource usage.


== Prerequisites

* You should have the **platform-admin** role on the {ks_product-en} platform. For more information, see link:../../../../../05-users-and-roles/01-users/[Users] and link:../../../../../05-users-and-roles/02-platform-roles/[Platform Roles].

* The host cluster and member clusters that need monitoring must have the Whizard Observability Center enabled.
+
--
// Note
include::../../../../../../_ks_components-en/admonitions/note.adoc[]

If the member cluster does not have the Whizard Observability Center enabled, the Whizard Observability Center will not be able to retrieve data from the member cluster.

include::../../../../../../_ks_components-en/admonitions/admonEnd.adoc[]
--


== Steps

include::../../../../../_custom-en/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

. Click image:/images/ks-qkcp/zh/icons/grid.svg[grid,18,18] in the upper-right corner of the page and click **Whizard Observability Center**.

+

include::../../../../../../_ks_components-en/oper-navigate.adoc[]

. View resource usage details under the **Clusters**, **Nodes**, **Projects**, and **Pods** tabs.
+
--
* Click **Select Cluster** and select the cluster you want to monitor.

* Click the dropdown list to set the sorting criteria.

include::../../../../../../_ks_components-en/oper-refreshListData.adoc[]

include::../../../../../../_ks_components-en/oper-customizeColumns.adoc[]
--