---
title: "Cross-cluster Pod Query"
keywords: "Kubernetes, {ks_product-en}, Whizard Observability Center, pods, query, cross-cluster"
description: "Describes how to query pods across clusters in the Whizard Observability Center."
weight: 01
---

// :ks_permission: **Alert Viewing**
:ks_navigation: **Resource Query > Pods**


This section describes how to query pods across clusters in the Whizard Observability Center.

For a single cluster, you can search for pods on the cluster's pod page by pod name and pod IP address.

For a multi-cluster environment, you can search for specific pod information across clusters in the Whizard Observability Center by pod name or pod IP address.


== Prerequisites

* You should have the **platform-admin** role on the {ks_product-en} platform. For more information, see link:../../../../../../05-users-and-roles/01-users/[Users] and link:../../../../../../05-users-and-roles/02-platform-roles/[Platform Roles].

* The host cluster and member clusters that need monitoring must have the Whizard Observability Center enabled.
+
--
// Note
include::../../../../../../../_ks_components-en/admonitions/note.adoc[]

If the member cluster does not have the Whizard Observability Center enabled, the Whizard Observability Center will not be able to retrieve data from the member cluster.

include::../../../../../../../_ks_components-en/admonitions/admonEnd.adoc[]
--


== Steps

include::../../../../../../_custom-en/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

+

. Click image:/images/ks-qkcp/zh/icons/grid.svg[grid,18,18] in the upper-right corner of the page and click **Whizard Observability Center**.

+

include::../../../../../../../_ks_components-en/oper-navigate.adoc[]
+
====
include::../../../../../../_custom-en/clusterManagement/pods/pods-para-podList_whizard.adoc[]

* Select a cluster from the dropdown list at the top left of the list to view pods in a specific cluster.

// include::../../../../../../_custom-en/clusterManagement/pods/pods-oper-searchForPods.adoc[]
* Click the search box above the list to search for pods by name, status, node, project, or pod IP address.

include::../../../../../../../_ks_components-en/oper-refreshListData.adoc[]

include::../../../../../../../_ks_components-en/oper-customizeColumns.adoc[]

* Click the pod name to enter the pod details page.

* Click the node name to enter the node details page.

====