---
title: "Remove Cluster Nodes"
linkTitle: "Remove Cluster Nodes"
keywords: "Kubernetes, KubeSphere, delete cluster node"
description: "Introduce how to delete KubeSphere cluster nodes."
weight: 02
---


This section describes how to delete KubeSphere cluster nodes.

The open-source tool KubeKey will be used during the process. For more information about KubeKey, please visit link:https://github.com/kubesphere/kubekey[GitHub KubeKey repository].

// Note
include::../../../../_ks_components-en/admonitions/note.adoc[]

The node deletion method described in this section is only applicable to Kubernetes installed through KubeKey. If your Kubernetes is not installed via KubeKey, please refer to link:https://kubernetes.io/zh/docs/concepts/architecture/nodes/[Kubernetes Documentation] to delete nodes.

include::../../../../_ks_components-en/admonitions/admonEnd.adoc[]

// Warning
include::../../../../_ks_components-en/admonitions/warning.adoc[]

* Do not delete control plane nodes, otherwise the cluster may encounter errors.

* Please ensure that after node deletion, the remaining resources in the cluster are still sufficient to run existing services. Otherwise, service interruption may occur after the node is deleted.

include::../../../../_ks_components-en/admonitions/admonEnd.adoc[]


== Prerequisites

:relfileprefix: ../../../

* You should get the installation configuration file **config-sample.yaml** and transfer it to the cluster node where you will perform this action. For more information, refer to xref:03-installation-and-upgrade/02-install-kubesphere/02-install-kubernetes-and-kubesphere.adoc[Install Kubernetes and {ks_product-en}].

:relfileprefix: ./

--
// Warning
include::../../../../_ks_components-en/admonitions/warning.adoc[]

If you are unable to get the installation configuration file **config-sample.yaml**, you need to refer to link:../../../03-installation-and-upgrade/02-install-kubesphere/02-install-kubernetes-and-kubesphere[Install Kubernetes and {ks_product-en}] to recreate the **config-sample.yaml** file. When recreating the file, make sure that the cluster information in the file matches the current state of the cluster. Otherwise, the uninstallation process may encounter errors.

include::../../../../_ks_components-en/admonitions/admonEnd.adoc[]
--


== Steps

include::../../../_custom-en/installationAndUpgrade/installationAndUpgrade-oper-downloadKubekey.adoc[]


. Execute the following command to get the name of the node that needs to be deleted:
+
--
// Bash
[,bash]
----
kubectl get node
----
--

. Execute the following command to evict the pods running on the node that needs to be deleted to other nodes (replace <node name> with the name of the node that needs to be deleted):
+
--
// Bash
[,bash]
----
kubectl drain <node name>
----
--

+

include::../../../_custom-en/installationAndUpgrade/installationAndUpgrade-oper-transferConfig.adoc[]

+

. Execute the following command to start deleting nodes:
+
--
// Bash
[,bash]
----
 ./kk delete node <node name> -f config-sample.yaml
----
--

. Execute the following command to view the current cluster nodes:
+
--
// Bash
[,bash]
----
kubectl get node
----

If the deleted node is not displayed, it means the node is deleted successfully.
--