// :ks_include_id: af7b991f4aa34769a70397593ae19d73
. 执行以下命令编辑安装配置文件 **config-sample.yaml**：
+
--
// Bash
include::../../../_ks_components/code/bash.adoc[]

vi config-sample.yaml

<<<<<<< HEAD
----
=======
include::../../../_ks_components/code/codeEnd.adoc[]
>>>>>>> 33f730a984ccbc140ff5c4d2867db9592a37f2e3

以下为部分示例配置文件，如需了解完整示例，请参阅link:https://github.com/kubesphere/kubekey/blob/master/docs/config-example.md[此文件]。

// Bash
include::../../../_ks_components/code/bash.adoc[]

apiVersion: kubekey.kubesphere.io/v1alpha2
kind: Cluster
metadata:
  name: sample
spec:
  hosts:
  - {name: node1, address: 192.168.6.6, internalAddress: 192.168.6.6, password: "Qcloud@123"}     # arm64 节点注意添加参数 arch: arm64
  roleGroups:
    etcd:
    - node1     
    control-plane:
    - node1
    worker:
    - node1
   # 如需使用 kk 自动部署镜像仓库，请设置该主机组 （建议仓库与集群分离部署，减少相互影响）     
    registry:     
    - node1
  controlPlaneEndpoint:
    ## Internal loadbalancer for apiservers
    #internalLoadbalancer: haproxy       # 如需部署高可用集群，且无负载均衡器可用，可开启该参数做集群内部负载均衡
    domain: lb.kubesphere.local
    address: ""
    port: 6443
  kubernetes:
    version: v1.23.15
    clusterName: cluster.local
  network:
    plugin: calico
    kubePodsCIDR: 10.233.64.0/18
    kubeServiceCIDR: 10.233.0.0/18
    ## multus support. https://github.com/k8snetworkplumbingwg/multus-cni
    enableMultusCNI: false
  registry:
    # 如需使用 kk 部署 harbor, 可将该参数设置为 harbor，不设置该参数且需使用 kk 部署容器镜像仓库，将默认部署 docker registry。
    # harbor 不支持 arm64, arm64 环境部署时，可不配置该参数。
    type: harbor
    # 如使用 kk 部署的 harbor 或其他需要登录的仓库，需设置对应仓库的 auths，如使用 kk 部署默认的 docker registry 仓库，则无需配置该参数。
    # 注意：如使用 kk 部署 harbor，该参数请于 harbor 启动后设置。
    auths:
      "dockerhub.kubekey.local": 
        username: admin
        password: Harbor12345
        plainHTTP: false  # 如果仓库使用 http，请将该参数设置为true
    privateRegistry: "dockerhub.kubekey.local"   # 设置集群部署时使用的私有仓库地址
    registryMirrors: []
    insecureRegistries: []
  addons: []

<<<<<<< HEAD
----
=======
include::../../../_ks_components/code/codeEnd.adoc[]
>>>>>>> 33f730a984ccbc140ff5c4d2867db9592a37f2e3


在 **spec:hosts** 参数下设置用于创建私有镜像服务的服务器的信息。

include::installationAndUpgrade-para-hosts.adoc[]

在 **spec:roleGroups:registry** 参数下设置用于创建私有镜像服务的服务器名称（将 <registry name> 替换为 **spec:hosts** 参数下设置的服务器实际名称）。

// YAML
include::../../../_ks_components/code/yaml.adoc[]

    registry:
    - <registry name>

<<<<<<< HEAD
----
=======
include::../../../_ks_components/code/codeEnd.adoc[]
>>>>>>> 33f730a984ccbc140ff5c4d2867db9592a37f2e3

将 **spec:registry:privateRegistry** 参数设置为私有镜像服务的地址 **dockerhub.kubekey.local**，然后保存文件。

// YAML
include::../../../_ks_components/code/yaml.adoc[]

  registry:
    registryMirrors: []
    insecureRegistries: []
    privateRegistry: dockerhub.kubekey.local

<<<<<<< HEAD
----
=======
include::../../../_ks_components/code/codeEnd.adoc[]
>>>>>>> 33f730a984ccbc140ff5c4d2867db9592a37f2e3
--

. 执行以下命令初始化私有镜像服务：
+
--
// Bash
include::../../../_ks_components/code/bash.adoc[]

 ./kk init registry -f config-sample.yaml -a kubekey-artifact.tar.gz

<<<<<<< HEAD
----
=======
include::../../../_ks_components/code/codeEnd.adoc[]
>>>>>>> 33f730a984ccbc140ff5c4d2867db9592a37f2e3

include::installationAndUpgrade-note-initializeRegistry.adoc[]
--