---
title: "启用 Whizard 可观测中心"
weight: 01
---

本节介绍如何配置相关扩展组件，以启用 Whizard 可观测中心。

为了使用 Whizard 可观测中心的完整功能，您需要安装并启用 WhizardTelemetry 平台服务、 WhizardTelemetry 监控以及 WhizardTelemetry 告警管理扩展组件，并进行以下配置。

== 前提条件

* 您需要在{ks_product_both}平台具有 **platform-admin** 角色。有关更多信息，请参阅link:../../../../05-users-and-roles/01-users/[用户]和link:../../../../05-users-and-roles/02-platform-roles/[平台角色]。
* 已安装 **WhizardTelemetry 平台服务**、 **WhizardTelemetry 监控**以及 **WhizardTelemetry 告警管理**扩展组件。

== 操作步骤

. 以具有 **platform-admin** 角色的用户登录{ks_product_left} Web 控制台。
. 点击**扩展中心**。
. 点击已安装的组件名称，进入组件详情页。
. 点击组件图标下的image:/images/ks-qkcp/zh/icons/more.svg[more,18,18]，选择**扩展组件配置**。
+
--
**WhizardTelemetry 平台服务**

将配置文件中的 `whizard-telemetry.config.observability.enabled` 参数设置为 true，然后点击**确定**。

[,yaml]
----
whizard-telemetry:
  config:
    observability:
      enabled: true
      endpoint: "http://query-frontend-whizard-operated.kubesphere-monitoring-system.svc:10902"
----
**WhizardTelemetry 监控**

修改配置文件的以下部分，然后点击**确定**。

[,yaml]
----
whizard-monitoring-helper:
  whizardHelper:
    enabled: true   ## set true to enable whizard

whizard:
  enabled: true  

frontend:
  enabled: true

whizardAgentProxy:
  enabled: true

whizard-agent-proxy:
  config:
    gatewayUrl: "http://172.31.73.206:30990"   ## set whizard gateway url，default is http://{host_cluster_node_ip}:30990

kube-prometheus-stack:
  prometheus:
    agentMode: true    # agentMode need to be set to true when enable whizard
----

**WhizardTelemetry 告警管理**

确保 `global.rules.distributionMode` 为 None。

[,yaml]
----
global:
  rules:
    distributionMode: None
----

--
. 编辑完成后，点击顶部导航栏上的image:/images/ks-qkcp/zh/icons/grid.svg[grid,18,18]图标，即可发现 **Whizard 可观测中心**图标。
+
--
[.admon.note,cols="a"]
|===
|说明

|
启用过程可能需要一定时间，请等待启用完成。
|===
--