---
title: "Set Up Feishu Notification"
keywords: "Kubernetes, {ks_product-en}, platform settings, notification management, notification settings, set up Feishu notification"
description: "Describes how to set up Feishu notification."
weight: 02
---


:ks_navigation: **Notification Management > Notification Channels**
:ks_permission: **Platform Settings Management**


This section describes how to set up Feishu notification.

Feishu notification functionality supports sending notifications to users through the following two methods:

* **Chat Settings**: Use a Feishu application to send notifications to specific users or departments.

* **Chatbot Settings**: Use a Feishu chatbot to send notifications to specific group chats.


== Prerequisites

* {empty}
include::../../../../../_custom-en/platformManagement/platformManagement-prer-requiredPermission_v4.adoc[]

* **WhizardTelemetry Notification** should have been installed and enabled.

* You should get the access parameters for the application or chatbot from Feishu in advance. For more information, see link:https://open.feishu.cn/document/ukTMukTMukTM/uITNz4iM1MjLyUzM[Feishu Developer Documentation].


== Steps

include::../../../../../_custom-en/platformManagement/platformManagement-oper-logIn.adoc[]

. Click image:/images/ks-qkcp/zh/icons/cogwheel.svg[cogwheel,18,18] in the upper-right corner of the {ks_product-en} web console to enter the **Platform Settings** page.

+

include::../../../../../../_ks_components-en/oper-navigate.adoc[]

+

. On the **Notification Channels** page, click the **Feishu** tab, set the Feishu notification parameters, and then click **OK**.
+
====
* Chat Settings
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

|App Key
|The App ID of the Feishu application.

|App Secret
|The App Secret of the Feishu application.

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sessionId.adoc[]
|===
--

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-groupChatBotSettings.adoc[]

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-notificationConditions_new.adoc[]

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sendTestInformation.adoc[]
====

. In the upper-right corner of the **Feishu** tab, click the toggle switch to set the Feishu notification to **Enabled**.