---
title: "Set Up DingTalk Notification"
keywords: "Kubernetes, {ks_product-en}, platform settings, notification management, notification settings, set up DingTalk notification"
description: "Describes how to set up DingTalk notification."
weight: 03
---

:ks_navigation: **Notification Management > Notification Channels**
:ks_permission: **Platform Settings Management**


This section describes how to set up DingTalk notification.

DingTalk notification functionality supports sending notifications to users through the following two methods:

* **Chat Settings**: Use a DingTalk application to send notifications to specific users or departments.

* **Chatbot Settings**: Use a DingTalk chatbot to send notifications to specific group chats.


== Prerequisites

* {empty}
include::../../../../../_custom-en/platformManagement/platformManagement-prer-requiredPermission_v4.adoc[]

* **WhizardTelemetry Notification** should have been installed and enabled.

* You should get the access parameters for the application or chatbot from DingTalk in advance. For more information, see link:https://open.dingtalk.com/document/orgapp-server/how-to-call-apis[DingTalk Developer Documentation].


== Steps

include::../../../../../_custom-en/platformManagement/platformManagement-oper-logIn.adoc[]

. Click image:/images/ks-qkcp/zh/icons/cogwheel.svg[cogwheel,18,18] in the upper-right corner of the {ks_product-en} web console to enter the **Platform Settings** page.

+

include::../../../../../../_ks_components-en/oper-navigate.adoc[]

+

. On the **Notification Channels** page, click the **DingTalk** tab, set the DingTalk notification parameters, and then click **OK**.
+
====
* Chat Settings
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

|App Key
|The App Key of the DingTalk application.

|App Secret
|The App Secret of the DingTalk application.

|Chat ID
|The Chat ID that will receive notifications. Click **Add** to set multiple Chat IDs.
|===
--

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-groupChatBotSettings.adoc[]

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-notificationConditions_new.adoc[]

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sendTestInformation.adoc[]
====


. In the upper-right corner of the **DingTalk** tab, click the toggle switch to set the DingTalk notification function to **Enabled**.