---
title: "Set Up WeCom Notification"
keywords: "Kubernetes, {ks_product-en}, platform settings, notification management, notification settings, set up WeCom notification"
description: "Describes how to set up WeCom notification."
weight: 04
---


:ks_navigation: **Notification Management > Notification Channels**
:ks_permission: **Platform Settings Management**


This section describes how to set up WeCom notification. After configuration, you can receive notification messages through WeCom chats or chatbots.


== Prerequisites

* {empty}
include::../../../../../_custom-en/platformManagement/platformManagement-prer-requiredPermission_v4.adoc[]

* **WhizardTelemetry Notification** should have been installed and enabled.

* You should get the access parameters for the WeCom application in advance. For more information, see link:https://developer.work.weixin.qq.com/document/path/90664[WeCom Developer Documentation].


== Steps

include::../../../../../_custom-en/platformManagement/platformManagement-oper-logIn.adoc[]

. Click image:/images/ks-qkcp/zh/icons/cogwheel.svg[cogwheel,18,18] in the upper-right corner of the {ks_product-en} web console to enter the **Platform Settings** page.

+

include::../../../../../../_ks_components-en/oper-navigate.adoc[]

+

. On the **Notification Channels** page, click the **WeCom** tab, set the WeCom notification parameters, and then click **OK**.
+
====
* Chat Settings > Server Settings
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

|Corp ID
|Your company's Corp ID on WeCom.

|Agent ID
|The Agent ID of the WeCom application.

|Secret
|The Secret of the WeCom application.
|===
--

* Chat Settings > Recipient Settings
+
--
Set the User ID, Department ID, or Tag ID that will receive notifications. Click **Add** to set multiple IDs.
--

* Chatbot Settings > Chatbot Settings
+
--
Webhook URL: The webhook address of the WeCom Chatbot.
--

* Chatbot Settings > Recipient Settings
+
--
Set the User ID or user phone number that will receive notifications. Click **Add** to set multiple IDs and phone numbers.
--


include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-notificationConditions_new.adoc[]

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sendTestInformation.adoc[]
====

. In the upper-right corner of the **WeCom** tab, click the toggle switch to set the WeCom notification function to **Enabled**.