---
title: "Set Up Slack Notification"
keywords: "Kubernetes, {ks_product-en}, platform settings, notification management, notification settings, set up Slack notification"
description: "Describes how to set up Slack notification."
weight: 05
---


:ks_navigation: **Notification Management > Notification Channels**
:ks_permission: **Platform Settings Management**


This section describes how to set up Slack notification.


== Prerequisites

* {empty}
include::../../../../../_custom-en/platformManagement/platformManagement-prer-requiredPermission_v4.adoc[]

* **WhizardTelemetry Notification** should have been installed and enabled.

* You should get the access parameters for the Slack application in advance. For more information, see link:https://api.slack.com/messaging/webhooks#create_a_webhook[Slack Developer Documentation].


== Steps

include::../../../../../_custom-en/platformManagement/platformManagement-oper-logIn.adoc[]

. Click image:/images/ks-qkcp/zh/icons/cogwheel.svg[cogwheel,18,18] in the upper-right corner of the {ks_product-en} web console to enter the **Platform Settings** page.

+

include::../../../../../../_ks_components-en/oper-navigate.adoc[]

+

. On the **Notification Channels** page, click the **Slack** tab, set the Slack notification parameters, and then click **OK**.
+
====
* Server Settings
+
--
Set the token used to access the Slack application.
--

* Slack Channel Settings
+
--
Set the Slack channels that will receive notifications. Click **Add** to set multiple Slack channels.
--

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-notificationConditions_new.adoc[]

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sendTestInformation.adoc[]
====

. In the upper-right corner of the **Slack** tab, click the toggle switch to set the Slack notification function to **Enabled**.