---
title: "Set Up Webhook Notification"
keywords: "Kubernetes, {ks_product-en}, platform settings, notification management, notification settings, set up Webhook notification"
description: "Describes how to set up Webhook notification."
weight: 06
---

:ks_navigation: **Notification Management > Notification Channels**
:ks_permission: **Platform Settings Management**


This section describes how to set up Webhook notification.


== Prerequisites

* {empty}
include::../../../../../_custom-en/platformManagement/platformManagement-prer-requiredPermission_v4.adoc[]

* **WhizardTelemetry Notification** should have been installed and enabled.

* You should get the access parameters for the Webhook in advance. For more information, please contact your Webhook administrator.


== Steps

include::../../../../../_custom-en/platformManagement/platformManagement-oper-logIn.adoc[]

. Click image:/images/ks-qkcp/zh/icons/cogwheel.svg[cogwheel,18,18] in the upper-right corner of the {ks_product-en} web console to enter the **Platform Settings** page.

+

include::../../../../../../_ks_components-en/oper-navigate.adoc[]

+

. On the **Notification Channels** page, click the **Webhook** tab, set the Webhook notification parameters, and then click **OK**.
+
====
* Server Settings
+
--
[%header,cols="1a,4a"]
|===
|Parameter |Description

|Webhook URL
|The access URL of the Webhook.

|Authentication Type
|The authentication type of the Webhook.

* **No Authentication**: No authentication is required.

* **Bearer Token**: Use a URL Bearer token for authentication. If you choose this type, you need to further set the token used for authentication.

* **Basic Authentication**: Use a username and password for authentication. If you choose this type, you need to further set the username and password used for authentication.

|Skip TLS Verification (Insecure)
|Whether to skip TLS verification when calling the Webhook.
|===
--

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-notificationConditions_new.adoc[]

include::../../../../../_custom-en/platformManagement/platformSettings/notificationChannels/notificationChannels-para-sendTestInformation.adoc[]
====

. In the upper-right corner of the **Webhook** tab, click the toggle switch to set the Webhook notification function to **Enabled**.