---
title: "Review App Versions"
keywords: "Kubernetes, {ks_product-en}, App Store, App Review, Review App Version"
description: "Describes how to review app versions submitted to the App Store."
weight: 01
---

:ks_navigation: **Application Review**
:ks_permission: **App Store Management**

This section describes how to review app versions submitted to the App Store.

== Prerequisites

* {empty}
include::../../../../../_custom-en/platformManagement/platformManagement-prer-requiredPermission_v4.adoc[]

* **KubeSphere App Store Management** should have been installed and enabled.

* An app version has been submitted to the App Store, and has not yet been reviewed.

== Steps

include::../../../../../_custom-en/platformManagement/platformManagement-oper-logIn.adoc[]

. Click image:/images/ks-qkcp/zh/icons/grid.svg[grid,18,18] in the upper-right corner and select **App Store Management**.

+

include::../../../../../../_ks_components-en/oper-navigate.adoc[]

+

. On the **New** tab, click the name of the app version you need to review.

. In the **App Details** page, review the app's information, then click **Reject** or **Approve** as needed.
+
--
// Note
include::../../../../../../_ks_components-en/admonitions/note.adoc[]

* If you click **Reject**, you need to further input the reason in the **Rejection Reason** dialog, then click **OK**.

* After the app version is approved, if you want to publish it in the App Store, the App Store administrator should also list it.

include::../../../../../../_ks_components-en/admonitions/admonEnd.adoc[]
--