---
title: "Delete Custom Rule Groups"
keywords: "Kubernetes, {ks_product-en}, cluster management, monitoring alerting, alert management, rule groups, delete rule groups"
description: "Describes how to delete alerting rule groups."
weight: 07
---

// :ks_permission: **Rule Group Management**
// :ks_menu: **Platform Management > Whizard Observability Center**
:ks_navigation: **Global Alerts > Custom Rule Groups**


This section describes how to delete alerting rule groups.

[.admon.note,cols="a"]
|===
|Note

|
{ks_product-en} only supports deleting custom rule groups, not built-in rule groups. You can reset built-in rule groups.
|===

[.admon.warning,cols="a"]
|===
|Warning

|
Rule groups cannot be recovered after deletion, so please proceed with caution.
|===

== Prerequisites

You should have the **platform-admin** role on the {ks_product-en} platform. For more information, see link:../../../../../../05-users-and-roles/01-users/[Users] and link:../../../../../../05-users-and-roles/02-platform-roles/[Platform Roles].


== Delete a Single Rule Group

include::../../../../../../_custom-en/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

+

. Click image:/images/ks-qkcp/zh/icons/grid.svg[grid,18,18] in the upper-right corner of the page and click **Whizard Observability Center**.

+

include::../../../../../../../_ks_components-en/oper-navigate.adoc[]

+

include::../../../../../../_custom-en/clusterManagement/ruleGroups/ruleGroups-oper-deleteASingleAlertingPolicy.adoc[]


== Delete Multiple Rule Groups

include::../../../../../../_custom-en/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

+

. Click image:/images/ks-qkcp/zh/icons/grid.svg[grid,18,18] in the upper-right corner of the page and click **Whizard Observability Center**.

+

include::../../../../../../../_ks_components-en/oper-navigate.adoc[]

+

include::../../../../../../_custom-en/clusterManagement/ruleGroups/ruleGroups-oper-deleteMultipleAlertingPolicies.adoc[]
