---
title: "Reset Built-in Rule Groups"
keywords: "Kubernetes, {ks_product-en}, cluster management, monitoring alerting, alert management, rule groups, delete rule groups"
description: "Describes how to reset built-in rule groups."
weight: 08
---

// :ks_permission: **Rule Group Management**
// :ks_menu: **Platform Management > Whizard Observability Center**
:ks_navigation: **Global Alerts > Built-in Rule Groups**


This section describes how to reset built-in rule groups.

[.admon.note,cols="a"]
|===
|Note

|
{ks_product-en} only supports resetting built-in rule groups, not custom rule groups.
|===

[.admon.warning,cols="a"]
|===
|Warning

|
Rule groups cannot be recovered after resetting, so please proceed with caution.
|===


== Prerequisites

You should have the **platform-admin** role on the {ks_product-en} platform. For more information, see link:../../../../../../05-users-and-roles/01-users/[Users] and link:../../../../../../05-users-and-roles/02-platform-roles/[Platform Roles].


== Steps

include::../../../../../../_custom-en/platformManagement/extensionManagement/extensionManagement-oper-logInAsPlatformAdmin.adoc[]

+

. Click image:/images/ks-qkcp/zh/icons/grid.svg[grid,18,18] in the upper-right corner of the page and click **Whizard Observability Center**.

+

include::../../../../../../../_ks_components-en/oper-navigate.adoc[]

. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] on the right side of the rule group you need to reset, and then select **Reset** from the dropdown list.

. In the **Reset Rule Group** dialog, click **OK**.