---
title: "Delete Volume Snapshot Classes"
keywords: "Kubernetes, {ks_product-en}, cluster management, storage, volume snapshot classes, delete volume snapshot class"
description: "Learn how to delete a volume snapshot class."
weight: 05
---

:ks_permission: **Volume Snapshot Classes Management**
:ks_navigation: **Storage > Volume Snapshot Classes**

This section describes how to delete a volume snapshot class.

// Warning
include::../../../../../_ks_components-en/admonitions/warning.adoc[]

After a volume snapshot class is deleted, the volume snapshots and volume snapshot contents created based on the volume snapshot class will not be deleted, but users will no longer be able to save snapshot data to the backend storage system through this volume snapshot class.

include::../../../../../_ks_components-en/admonitions/admonEnd.adoc[]


== Prerequisites

* **KubeSphere Storage** should have been installed and enabled.

* {empty}
include::../../../../_custom-en/clusterManagement/clusterManagement-prer-requiredPermission_new.adoc[]


== Delete a Single Volume Snapshot Class

include::../../../../_custom-en/clusterManagement/clusterManagement-oper-openClusterPage.adoc[]

+

include::../../../../../_ks_components-en/oper-navigate.adoc[]

+

. Click image:/images/ks-qkcp/zh/icons/more.svg[more,18,18] on the right side of the volume snapshot class you want to delete, then select **Delete** from the dropdown list.

. In the **Delete Volume Snapshot Class** dialog, enter the name of the volume snapshot class, then click **OK**.


== Delete Multiple Volume Snapshot Classes

include::../../../../_custom-en/clusterManagement/clusterManagement-oper-openClusterPage.adoc[]

+

include::../../../../../_ks_components-en/oper-navigate.adoc[]

+

. Select the checkbox on the left side of the volume snapshot classes you want to delete, then click **Delete** above the list.

. In the **Delete Multiple Volume Snapshot Classes** dialog, enter the name of the volume snapshot, then click **OK**.
+
--
include::../../../../_custom-en/note-separateNamesByComma.adoc[]
--